### ISSUE TITLE
建议增加配置选项用于搜索引擎的验证

### ISSUE THREAD

**Issue by ADD-SP** [YunYouJun/hexo-theme-yun#10]
1. 如果想让网站被Google收录则需要经过验证。
2. 验证的一个步骤就是就是添加<meta>标签，如
```
<meta name='google-site-verification' content='XXXXX' />
```
3. 虽然也有其它的方式验证，但是都不大好用。
4. 目前还没发现主题中有这个配置选项，只能手动更改，如下图
![Snipaste_2020-03-28_13-39-19](https://user-images.githubusercontent.com/44437200/77816072-c061ef00-70fa-11ea-8c15-98baecace85c.png)
5. 其它搜索引擎收录也需要做类似的验证，如果可以通过配置来实现会方便一些。比如在拉取最新主题的时候会更方便。

**Comment by YunYouJun** [comment]
emm，这个我也考虑过。不过我记得验证站点有三种方式。
一种是添加 DNS  TXT 解析。（这个可能算是最为麻烦，还要打开域名服务商什么的。但也是对站点本身影响最小的一个。）
第二种是你提到的这种添加 `meta` 信息，我之所以没有添加这个方式，是因为这个 meta 部分信息，只对验证 google 站点有用，对于用户来说完全是多余的。而 Hexo 是静态站点生成器，通过这一方法来验证，就意味着整个站点所有静态文件头部都会带上这一信息。譬如一百多篇文章加分页加标签页等等，就相当于凭空增加了上百行，而这对用户来说完全没有必要，所以我觉得可能不适合使用这种方式来进行站点验证。
第三种，在站点下上传指定的 HTML 文件，其实这个我觉得麻烦程度应当与第二种一致，我们只要下载该文件，然后将其放在 Hexo 工作目录的 `source` 文件夹下就可以来，会被自动拷贝过去部署。

---

谢谢你的建议，如果你有什么不同的见解，欢迎讨论。

**Comment by YunYouJun** [comment]
发现现在还有了第四种方案，通过 Google Analytics（分析）验证。
对于已安装了 Google Analytics（分析）的同学来说，直接点击一键认证。最为方便。

> 我可以去把我的解析删掉了……

**Comment by ADD-SP** [comment]
> emm，这个我也考虑过。不过我记得验证站点有三种方式。
> 
> * 一种是添加 DNS  TXT 解析。（这个可能算是最为麻烦，还要打开域名服务商什么的。但也是对站点本身影响最小的一个。）也是我目前使用的方式。
> * 第二种是你提到的这种添加 `meta` 信息。
>   
>   * 我之所以没有添加这个方式，是因为这个 meta 部分信息，只对验证 google 站点有用，对于用户来说完全是多余的。
>   * 而 Hexo 是静态站点生成器，通过这一方法来验证，就意味着整个站点所有静态文件头部都会带上这一信息。譬如一百多篇文章加分页加标签页等等，就相当于凭空增加了上百行代码，而这对用户来说完全没有必要。
>   * 所以我觉得可能不适合使用这种方式来进行站点验证。
> * 第三种，在站点下上传指定的 HTML 文件，其实这个我觉得麻烦程度应当与第二种一致，我们只要下载该文件，然后将其放在 Hexo 工作目录的 `source` 文件夹下就可以来，会被自动拷贝过去部署。
> 
> 所以相比之下，直接使用第三种方式或许最好，且不需要对主题进行侵入式修改，也不会过于增加生成后的静态文件大小，
> 
> 谢谢你的建议，如果你有什么不同的见解，欢迎讨论。

我最初确实是打算直接拷贝html文件过去，可是会发现生成的文件会被修改导致无法验证，下图为源文件和`hexo g`生成的文件
![Snipaste_2020-03-28_15-12-56](https://user-images.githubusercontent.com/44437200/77817550-af1edf80-7106-11ea-9ce4-4d37f7dbd37f.png)
![Snipaste_2020-03-28_15-12-33](https://user-images.githubusercontent.com/44437200/77817551-b0e8a300-7106-11ea-8d48-3caf112472fd.png)

**Comment by YunYouJun** [comment]
@ADD-SP 以前谷歌验证是不带后缀名的文件，所以没有影响。而现在是 html 文件，被 hexo 自动编译了。

参考[配置文档](https://hexo.io/docs/configuration#Directory)
添加 skip_render 即可。

> 这里指的是 Hexo 工作目录下的 `_config.yml` 文件。

谢谢你的反馈，此后我将添加一些关于此方面的解释说明到主题文档中。

**Comment by ADD-SP** [comment]
> @ADD-SP 以前谷歌验证是不带后缀名的文件，所以没有影响。而现在是 html 文件，被 hexo 自动编译了。
> 
> 参考[配置文档](https://hexo.io/docs/configuration#Directory)
> 添加 skip_render 即可。
> 
> > 这里指的是 Hexo 工作目录下的 `_config.yml` 文件。
> 
> 谢谢你的反馈，此后我将添加一些关于此方面的解释说明到主题文档中。

emmm，看验证方式的时候偷懒没拖滚动条。现在直接用Google Analytics验证了。

谢了，主题很漂亮很好用。

我把issue关了，因为现有的问题均得到解决。
