### ISSUE TITLE
[Usage Problem] Markdown語法在在線&本地網頁上部分失效

### ISSUE THREAD

**Issue by yyyyyyounger** [YunYouJun/hexo-theme-yun#100]
- 主题版本号： v1.4.0
- 遇到的问题： Markdown語法在hexo渲染出網站後失效：好像就在昨天在`yun.yml`部署完jsDelivr的CDN並deploy之後，通過`hexo s`生成的本地頁面和在線頁面都出現了Markdown語法部分失效的情況。
  目前有` ``` `的用法可以在網頁中正常顯示代碼引用，*或者-亦正常標註，但\` 的用法、製表符的代碼引用用法、`>`的區塊引用用法等均失效
  
  - 截图：直接點開鏈接即可，就像是 `.md` 變成了 `.txt`
  - hexo代码仓库: https://github.com/yyyyyyounger/yyyyyyounger.github.io/blob/hexo/source/_posts/0120_JavaScript.md
    - 甚至這個鏈接點開是GitHub的markdown預覽也是正確的，就hexo無了
  - 线上预览地址: https://yyyyyyounger.github.io/2021/01/20/0120_JavaScript/

- 我是在VS Code中進行網站佈置，並且裝有預覽的插件(Markdown Preview Enhanced)，**所有博客在預覽下的Markdown語法都正確表示**，唯有生成後的頁面MK語法失效。
- 猜測過是代碼高亮(highlight)的問題，但所有的開關情況嘗試過後仍然有此問題（但我覺得這是Markdown語法啊，不應該直接識別並渲染才對嗎
- 網絡上沒有相關案例，想問問是否是該主題某項配置出現了問題，存在還需要配置的項目..百思不得其解 小白苦惱

期待作者大大的回復！謝謝！

**Comment by yyyyyyounger** [comment]
我剛嘗試換了主題..問題已經解決了..而且不小心deploy了，上面的鏈接可能不受用了

**Comment by YunYouJun** [comment]
Yeah, good luck.
