### ISSUE TITLE
[Bug Report] 代码段复制按钮会随下方滚动条移动

### ISSUE THREAD

**Issue by Yogile** [YunYouJun/hexo-theme-yun#106]
问题页面 URL：https://hexo.yogile.icu/Linux/bootstrap-send-netrequest-linux/
截图
![t.png](https://i.loli.net/2021/02/12/Ml1dhIKmFWjxk8S.png)

**Comment by YunYouJun** [comment]
Thanks. Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/ef70cf13fe2298fc54303e2878dff524e1cd5a9a.
