### ISSUE TITLE
[Bug Report] 在首页 page 2 以上页面时，使用搜索栏搜索结果跳转 URL 多出 `/page/2/`。

### ISSUE THREAD

**Issue by Yogile** [YunYouJun/hexo-theme-yun#107]
版本：dev 1.5.0 
问题页面：https://hexo.yogile.icu/page/2/
问题说明：在 **非 page 1 首页页面** 或者 **某一文章页面内** 使用搜索功能搜索本地页面时，会将目标 uri 路径添加到当前路径末尾，导致访问 404 。
- 搜索示例：
  <a href="https://sm.ms/image/l37H54DUBdkjRMn" target="_blank"><img src="https://i.loli.net/2021/02/14/l37H54DUBdkjRMn.png" style="zoom:80%;" /></a>

截图：
<a href="https://sm.ms/image/vEmUlPuRDIHOy8n" target="_blank"><img src="https://i.loli.net/2021/02/14/vEmUlPuRDIHOy8n.png" style="zoom:80%;" /></a>
<a href="https://sm.ms/image/MKXtEQPxA74GjZm" target="_blank"><img src="https://i.loli.net/2021/02/14/MKXtEQPxA74GjZm.png" style="zoom:80%;" /></a>

**Comment by YunYouJun** [comment]
Fixed.
