### ISSUE TITLE
安装后使用主题的问题

### ISSUE THREAD

**Issue by Bennett-Q** [YunYouJun/hexo-theme-yun#114]
- 主题版本号（必须）： v1.5.1
- 您遇到的问题（必须）： 在执行 hexo g 命令时报错
  - 截图（可选）
  -
![微信截图_20210316150029](https://user-images.githubusercontent.com/52900353/111268931-e7496600-8668-11eb-8dec-6c8b470aeb21.png)

  - 代码仓库（可选）
  - 线上预览地址（可选）
- 您期待的结果（必须）：我希望能够正常使用主题。
- 您所尝试的操作（可选）：我尝试了重新clone，但是木有用。

**Comment by Bennett-Q** [comment]
我在想是不是需要连同index.html一起修改，如果需要修改的话，会不会很麻烦

**Comment by YunYouJun** [comment]
配置错了吧，配置了某个带有 `appID` 的功能，但是没写 `appID`。

**Comment by Bennett-Q** [comment]
我本身是默认的主题，换了yun主题后还要配置这个appID吗

**Comment by YunYouJun** [comment]
发一下 `yun.yml` 仓库链接看看。

不配置 `appID` 就把空的那个配置项删掉。

**Comment by Bennett-Q** [comment]
原因找到了，是因为我配置文件里algolia_search 和 wordcount没有删掉，但是其他地方又没有配置，这个也不知道怎么配置。

**Comment by YunYouJun** [comment]
用不着就不用配置。
