### ISSUE TITLE
[Bug Report] 文章左侧导航栏出现 bug

### ISSUE THREAD

**Issue by BestGuo2020** [YunYouJun/hexo-theme-yun#115]
hexo 版本为：v5.4.0 
主题为：v1.5.2

这个是我今天写的一篇日志：https://www.bestguo.top/2021/04/14/spring-aop-notion/

然而左侧的导航栏出现了下图问题

![QQ截图20210414181448](https://user-images.githubusercontent.com/45250038/114695436-34932300-9d4e-11eb-8a88-edf08b09887a.jpg)

**Comment by YunYouJun** [comment]
应该是自身的 markdown 文本有问题。请检查 Markdown 源文本，或粘贴在这里看看。

**Comment by BestGuo2020** [comment]
> 应该是自身的 markdown 文本有问题。请检查 Markdown 源文本，或粘贴在这里看看。
> 
> > Markdown 标题前后需换行

可是我标题前后的确是有换行的，以下是这篇日志出现上述问题的那段：
```
#### 示例总结

上面的权限验证的场景也是自己想出来的，我自己能够真真正正的体会到 AOP 的编写方法，同时也对上面的概念进行了一个类比，我觉得这里面的示例代码拿过来复制运行一下，体会体会并理解 aop 的道理，其实还是很重要的。

## 后记

自己在思考的过程中也想到过很多的类比方式，比如用牙签串起来的汉堡，羊肉串，西瓜，豆沙包，饺子等等。只要能真正的弄懂，那才是王道。

在理解 AOP 以及使用场景，参考了以下资料

- [细说Spring——AOP详解（AOP概览）](https://blog.csdn.net/q982151756/article/details/80513340)
- [13-SpringAOP最强大的通知-环绕通知](https://blog.csdn.net/happy_coding_life/article/details/80353009)
- [Spring AOP 五大通知类型](https://www.cnblogs.com/chuijingjing/p/9806651.html)
- [Spring AOP（通知、连接点、切点、切面）](https://www.cnblogs.com/sandea/p/11175834.html)
- [spring aop 及实现方式](https://www.jianshu.com/p/5b9a0d77f95f)

```
怕大佬看不出来，顺便将原来的 markdown 也上传了一份
[spring-aop-notion.md](https://github.com/YunYouJun/hexo-theme-yun/files/6310654/spring-aop-notion.md)

**Comment by YunYouJun** [comment]
我测试了下，应该是 `后记` 前的层级关系不对。

![image](https://user-images.githubusercontent.com/25154432/114709051-b12dfd80-9d5e-11eb-90df-bf40b7d2994b.png)

二级标题后应该用三级标题，而非四级标题。
修改后可正常显示。

![image](https://user-images.githubusercontent.com/25154432/114709134-cdca3580-9d5e-11eb-8a85-76a2d3440f5c.png)

**Comment by BestGuo2020** [comment]
> 我测试了下，应该是 `后记` 前的层级关系不对。
> 
> ![image](https://user-images.githubusercontent.com/25154432/114709051-b12dfd80-9d5e-11eb-90df-bf40b7d2994b.png)
> 
> 二级标题后应该用三级标题，而非四级标题。
> 修改后可正常显示。
> 
> ![image](https://user-images.githubusercontent.com/25154432/114709134-cdca3580-9d5e-11eb-8a85-76a2d3440f5c.png)

好嘞，我这就去改正过来，非常感谢云游君大佬 😊😊😊
