### ISSUE TITLE
在markdown中使用<img>会出现多余的文本

### ISSUE THREAD

**Issue by ADD-SP** [YunYouJun/hexo-theme-yun#12]
Markdown本身已经相当方便了，但是确实有一些需求要用嵌入HTML来实现。
***
主题版本：最新的dev版本
OS：Windows10 X64 1909
浏览器：Microsoft Edge 版本 80.0.361.69 (官方内部版本) (64 位)
复现步骤：
1. 启动主题的“图片懒加载”功能
2. 新建一个类似这样的文章
```
---
title: test
katex: true
categories:
  - test
date: 2020-03-30 13:52:31
---
<img src="https://images8.alphacoders.com/106/1069766.jpg">
<!--more-->
```
3. `hexo g`，`hexo s`，查看新建的文章界面会出现多余文本，如下图
![Snipaste_2020-03-30_14-19-24](https://user-images.githubusercontent.com/44437200/77881488-ad355780-7291-11ea-9d75-415a4cd0bc62.jpg)

**Comment by YunYouJun** [comment]
插入图片可以直接使用 `![图片](https://images8.alphacoders.com/106/1069766.jpg)` 插入，请问具体是什么情况下会需要使用使用 `img` 插入？

> 问题可以复现，原因是我写了一个正则替换来为所有插入的图片自动设置懒加载属性。
> 进群 389401003 即时讨论吧（我先睡个午觉

**Comment by YunYouJun** [comment]
大部分情况下，不需要手动插入 `img` 标签实现。
```html
<a href="">
  <img src=""/>
</a>
```

可以通过 `[![]()]()` 嵌套方式实现。

以及该 BUG 已通过简化原先的正则表达式修复。
可见 commit https://github.com/YunYouJun/hexo-theme-yun/commit/1403153d4f2d70a7b268e3364a09e8d315bdc37d 。
