### ISSUE TITLE
[Bug Report] LaTex Style Cannot Render Correctly When pjax Is On

### ISSUE THREAD

**Issue by leostudiooo** [YunYouJun/hexo-theme-yun#120]
# Bug Description

If you click an article from the home page, the style of LaTeX cannot be rendered correctly when `pjax` and `katex` are both set to be active. You have to refresh the page before you see the LaTeX expressions be rendered correctly.

![image](https://user-images.githubusercontent.com/35419343/116992266-57d73f80-ad08-11eb-85c1-d2ad71492a9b.png)
Before refreshing

![image](https://user-images.githubusercontent.com/35419343/116992359-73dae100-ad08-11eb-9596-420d021432f0.png)
After refreshing

# Reproduction

Set `pjax` and `katex` to true in `yun.yml` and render a page with some LaTeX expressions inside. Then open the page from the home page.

# Versions

- OS: Windows 10 Home CN 20H2, 19042.928
- Yun: v1.5.1
- Hexo: 5.2.0
- Node: 14
- Chrome: 90.0.4430.93, x64

# My Suggestion

Maybe loading `katex` in the first place can be a better choice.

# My Repository (if necessary)

https://github.com/leostudiooo/leostudiooo.github.io

The source code is at the branch `source` and the branch `master` is used to publish the website.

**Comment by sanshiliuxiao** [comment]
I fixed the bug and waited for YunYouJun to agree to merge

**Comment by leostudiooo** [comment]
Thanks a lot!

Sent from my Huawei phone

**Comment by YunYouJun** [comment]
Fixed in #121.
