### ISSUE TITLE
阅读更多按钮及烟花效果未出现

### ISSUE THREAD

**Issue by webyang-male** [YunYouJun/hexo-theme-yun#122]
版本:v1.6.0
问题:readmore阅读更多按钮和烟花效果在更改配置文件后未能出现
阅读更多按钮报错图片:
![image](https://user-images.githubusercontent.com/52821367/117227124-b4da0f00-ae48-11eb-9feb-37ccd6658d14.png)
预览网址:zzychaser.top
自定义配置文件:
[data自定义配置.zip](https://github.com/YunYouJun/hexo-theme-yun/files/6431073/data.zip)

**Comment by webyang-male** [comment]
[字符函数和字符串函数.md](https://github.com/YunYouJun/hexo-theme-yun/files/6431423/default.md)

**Comment by YunYouJun** [comment]
Fixed.
