### ISSUE TITLE
如何自定义我的代码块？或者yun有提供代码块样式的切换功能吗？

### ISSUE THREAD

**Issue by Anduin9527** [YunYouJun/hexo-theme-yun#123]
- 主题版本号（必须）： v 1.6.1
- 您期待的结果（必须）：我希望能够得到 自定义代码块字体，背景色或者使用别的样式的功能。

刚接触前端，所以不会自己写CSS(捂脸逃)

**Comment by YunYouJun** [comment]
见文档 [代码高亮](https://yun.yunyoujun.cn/guide/config.html#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE)。

Prismjs 主题可以参见 <https://cdn.jsdelivr.net/npm/prismjs@latest/themes/>.
