### ISSUE TITLE
在代码块中无法解析出C语言头文件

### ISSUE THREAD

**Issue by azeng233** [YunYouJun/hexo-theme-yun#124]
您需要提供的内容：

- 主题版本号（必须）： v1.6.0
- 您遇到的问题（必须）： 我遇到了代码块无法解析C头文件问题。
  - https://zengchen233.cn/posts/5915bcab/
- 您期待的结果（必须）：希望可以自定义代码风格 类似于Next主题的四个代码风格

您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by YunYouJun** [comment]
见[代码高亮](https://yun.yunyoujun.cn/guide/config.html#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE)。

![image](https://user-images.githubusercontent.com/25154432/118802984-62cbcb80-b8d5-11eb-8043-1edff39132be.png)
