### ISSUE TITLE
代码块溢出页面宽度如何解决呀？

### ISSUE THREAD

**Issue by winsight** [YunYouJun/hexo-theme-yun#125]
![image](https://user-images.githubusercontent.com/75029070/118369919-eb95ef00-b5d7-11eb-88b2-044a3f66762a.jpeg)

**Comment by YunYouJun** [comment]
请根据主题文档，开启代码高亮。

> https://yun.yunyoujun.cn/guide/config.html#%E4%BB%A3%E7%A0%81%E9%AB%98%E4%BA%AE
