### ISSUE TITLE
[Bug Report]启用pjax后无法正常加载评论

### ISSUE THREAD

**Issue by TennousuAthena** [YunYouJun/hexo-theme-yun#127]
如题，启用pjax后无法正常加载评论，已尝试utterances twikoo都会出现此问题

**Comment by YunYouJun** [comment]
因为最近比较忙，且我自身并未使用该几款评论，将会较迟修复该问题。
PR is welcome.

**Comment by TennousuAthena** [comment]
一个可行的方法：尝试把所有变量都放到window.下

见 https://github.com/TennousuAthena/tennousuAthena.github.io/commit/ad054f77c558dbfb1c6d33a6f7fd8da7d4bff880

（以twikoo为例

https://lemoe.cn/

**Comment by YunYouJun** [comment]
Hello，测试可行的话，是否有兴趣提供 PR？

**Comment by YunYouJun** [comment]
已尝试修复该问题，如果仍有问题，可在此反馈。
