### ISSUE TITLE
[Bug Report]yun主题不蒜子有问题

### ISSUE THREAD

**Issue by miaoermua** [YunYouJun/hexo-theme-yun#130]
如题，我这里使用不蒜子会报错没法提交，删除配置就没事，修改全部在yun.yml进行，不知道是不是我电脑环境的问题

**Comment by YunYouJun** [comment]
所提供的信息太少。请至少提供错误信息，预览图，可复现的配置代码等相关内容。

**Comment by YunYouJun** [comment]
如果您无法提供更多的可复现内容，我将关闭该 ISSUE。
