### ISSUE TITLE
[BUG REPORT] 标语动画不能正常出现

### ISSUE THREAD

**Issue by webyang-male** [YunYouJun/hexo-theme-yun#131]
环境:
   电脑:win10
   主题:最新版本(非稳定版)
  谷歌浏览器:版本 92.0.4484.7（正式版本） （64 位）

问题:

1. 初始/第一次打开网站标语动画不能出现---概率较高
2. 浏览博客直接返回主页或者浏览器返回不能出现---100%

截图:
![主页](https://user-images.githubusercontent.com/52821367/119246871-9fd6dd00-bbb7-11eb-9529-b00bd0204047.png)

尝试:

1. 清除浏览器缓存---不能解决
2. 刷新浏览器---功能正常(只有每次刷新才能100%解决)

**Comment by leostudiooo** [comment]
我刚好也想提这个 issue 来着。
可以复现。
如图，从博客文章页面后退回主页就会发生这样的错误。
![image](https://user-images.githubusercontent.com/35419343/119249595-47f6a100-bbcc-11eb-9c9c-4c42bd03c36e.png)
![image](https://user-images.githubusercontent.com/35419343/119249599-4d53eb80-bbcc-11eb-9e11-68af7fb7e194.png)

**Comment by YunYouJun** [comment]
是否都开启了 PJAX？

**Comment by webyang-male** [comment]
开了pjax

**Comment by leostudiooo** [comment]
开了的，因为我加了播放器

Sent from my Huawei phone


-------- Original message --------
From: 云游君 ***@***.***>
Date: Sun, May 23, 2021, 14:06
To: YunYouJun/hexo-theme-yun ***@***.***>
Cc: Leo Lingfeng Li ***@***.***>, Comment ***@***.***>
Subject: Re: [YunYouJun/hexo-theme-yun] 标语动画不能正常出现 (#131)

是否都开启了 PJAX？

―

**Comment by webyang-male** [comment]
> 是否都开启了 PJAX？

开了,同上

**Comment by YunYouJun** [comment]
应该是 PJAX 的兼容问题，待修复。

**Comment by YunYouJun** [comment]
Fixed. 您可以尝试 dev 分支。正式版本将在下个月 Release。

**Comment by leostudiooo** [comment]
Thx! 辛苦了
