### ISSUE TITLE
[Usage Problem]hexo generate中出现的问题

### ISSUE THREAD

**Issue by Win-X** [YunYouJun/hexo-theme-yun#133]
![image](https://user-images.githubusercontent.com/58622317/122633770-d1868980-d10c-11eb-898c-f939b1952b26.png)
![image](https://user-images.githubusercontent.com/58622317/122633778-e6631d00-d10c-11eb-94bc-a56c70764294.png)
显示这些错误，原来的主题文件夹已经删除并且重新clone了，重新clone完之后是这样的
请问是什么原因，该怎么解决呢

**Comment by YunYouJun** [comment]
控制台显示存在字符未正确使用的问题。

此外，请提供最小可复现仓库。

**Comment by Win-X** [comment]
刚刚一段一段注释着试，发现是这一块的问题，如果注释掉就正常了
![image](https://user-images.githubusercontent.com/58622317/122642627-f3e4cb00-d13d-11eb-906a-6eabc717ac42.png)

**Comment by YunYouJun** [comment]
应该是之前锁进有问题吧。

**Comment by Win-X** [comment]
缩进的话，我不太清楚缩进格式，不过把这三段引用全注释掉的话，也不用在在意注释，就可以正常使用
