### ISSUE TITLE
[Bug Report] 评论系统切换出现共存的问题

### ISSUE THREAD

**Issue by BestGuo2020** [YunYouJun/hexo-theme-yun#141]
**bug 描述**
当我切换到 livere 的时候，发现 waline 和 livere 两个评论系统都存在。

![image](https://user-images.githubusercontent.com/45250038/125789434-c62e2bdc-fe79-4d90-875a-1198764311f2.png)

所有的页面都是这样的问题。以下找了文章页和相册页。

[文章页](https://blog.bestguo.top/2021/07/08/request-method-POST-not-supported-resolved/)

![image](https://user-images.githubusercontent.com/45250038/125790926-3293d6ef-d649-400a-b6e6-d9a5c3c04491.png)

[相册页](https://blog.bestguo.top/albums/)

![image](https://user-images.githubusercontent.com/45250038/125791042-1c9b763d-ede9-4309-9b52-69d6a7bd0431.png)

**发生问题的版本**
Hexo 版本 5.4.0
Yun 主题版本 1.6.1

**Comment by YunYouJun** [comment]
是否已开启 PJAX？

**Comment by BestGuo2020** [comment]
> 是否已开启 PJAX？

没有开启 pjax

**Comment by BestGuo2020** [comment]
> 是否已开启 PJAX？

我刚刚试了试把 pjax 开启还是一样的🤔

**Comment by YunYouJun** [comment]
已复现，待解决。

**Comment by BestGuo2020** [comment]
> 已复现，待解决。

好嘞~
😊

**Comment by YunYouJun** [comment]
> > 已复现，待解决。
> 
> 好嘞~
> 😊

已修复，可尝试切换至 dev 分支使用。
