### ISSUE TITLE
[Bug Report] 多行 LateX 渲染不能

### ISSUE THREAD

**Issue by leostudiooo** [YunYouJun/hexo-theme-yun#144]
**Describe the bug**
如题。
![image](https://user-images.githubusercontent.com/35419343/127729351-44cfdd9b-1ef1-4f8f-ac57-e6b383e798a4.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/35419343/127729359-da46ca58-1692-4f66-9ad6-1174d77af09c.png)

**Desktop (please complete the following information):**

- OS: 
  版本			Windows 11 专业工作站版
  版本			21H2
  安装日期		‎2021/‎7/‎2
  操作系统版本	22000.100
  序列号			PF1SQ3XR
  体验			Windows Feature Experience Pack 421.18901.0.3

- Browser: Google Chrome 92.0.4515.107 x64

**Repo**
https://github.com/leostudiooo/leostudiooo.github.io/
Branch: Source

**Comment by leostudiooo** [comment]
出问题的 LaTeX 代码：

```tex
$$\begin{equation}
	\left\{
		\begin{aligned}
			x=a\cos\theta\\
			y=b\sin\theta\\
		\end{aligned}
	\right.
\end{equation}$$
```

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/127735062-93bc4d00-82cb-4975-be0c-ba1db53ad91b.png)

使用 `<div>` 包裹一下即可

```html
<div>
$$
\begin{equation}
	\left\{
		\begin{aligned}
			x=a\cos\theta\\
			y=b\sin\theta\\
		\end{aligned}
	\right.
\end{equation}
$$
</div>
```

这是解析 hexo 的 markdown 会自动给换行的字符串添加 p 标签之类，导致 katex 无法将其识别为一个整体。
暂时没想到更好的解决办法。

> 对了 快把你的 tab 调成空格！

**Comment by leostudiooo** [comment]
get.

**Comment by leostudiooo** [comment]
参考一下 [Markdown Preview Enhanced (MPE)](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) 这个 VS Code 扩展的思路呢？这段 LaTeX 在里面是能够被正常渲染的。

**Comment by YunYouJun** [comment]
> 参考一下 [Markdown Preview Enhanced (MPE)](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) 这个 VS Code 扩展的思路呢？这段 LaTeX 在里面是能够被正常渲染的。

其实主要是 hexo 的局限性，它的渲染流程以及一些开发方式/特性对于现在其实已经比较落后了，想要达到理想的效果不得不对 hexo 本身进行一些改造。有些积重难返。
所以未来我可能打算迁移到 Vuepress 主题的构建上。
