### ISSUE TITLE
无法commit themes文件夹

### ISSUE THREAD

**Issue by MerakW** [YunYouJun/hexo-theme-yun#145]
<无法将themes/yun commit>

您需要提供的内容：

- 主题版本号（必须）： v1.6.0
- 您遇到的问题（必须）： 使用githubdescktop客户端无法将themes/yun pull上去
  - 截图（可选）
[![WxDQZ6.png](https://z3.ax1x.com/2021/08/01/WxDQZ6.png)](https://imgtu.com/i/WxDQZ6)
- 您期待的结果：我希望能够得到帮助
- 您所尝试的操作（可选）：我尝试删除了themes下的.gitkeep文件,但是仍然无法上传
- 尝试了 git add /themes ,仍然无法上传

**Comment by YunYouJun** [comment]
`themes/yun` 是一个 git 仓库，内容与 `hexo-theme-yun` 完全相同，无需将其上传至 git 仓库。

**Comment by MerakW** [comment]
主要问题是我需要将我的博客部署到netlify上 所以需要pull上去
如果不pull的话netlify就显示build失败了

**Comment by YunYouJun** [comment]
可添加 gitsubmodules。[faq](https://github.com/YunYouJun/yunyoujun.github.io#faq)

```bash
git submodule add https://github.com/YunYouJun/hexo-theme-yun themes/yun
```

这是我部署于 netlify 上的镜像，可正常部署。
> https://yunyoujun.netlify.app/

---

如果您实在想要将代码上传至 git 仓库，您可以删除 themes/yun 下存在的 `.git` 文件夹，再重新提交。

**Comment by MerakW** [comment]
好的 谢谢dalao
