### ISSUE TITLE
[Bug Report] 文章type属性 - 新增的自定义type无效

### ISSUE THREAD

**Issue by Reimirno** [YunYouJun/hexo-theme-yun#146]
### 问题

文章的type属性设置为内置的`type`种类（如`bilibili`，`zhihu`等）时图标、颜色可以正确渲染。按照Doc的指示在`yun.yml`中引入了自定义的属性却无法正确显示，会fall back成默认的蓝色外链。

### 代码

在`yun.yml`中，我添加了如下行：
```
type:
  testtype:
    color: '#4382aa'
    icon: icon-bilibili-line
```
hexo new一个post，front matter中加入如下两行：
```
type: testtype
url: https://store.steampowered.com/app/1260810/2/
```
### 效果

在本地hexo s的效果就是没有检测到testtype，直接使用了默认的外链类型。
首页上
![image](https://user-images.githubusercontent.com/82516689/128209349-14abea81-8858-4a63-bade-f1dfd6b7b307.png)

Archive中
![image](https://user-images.githubusercontent.com/82516689/128209260-1ea03fe4-8f13-42a2-ba63-3447740f04d5.png)

Post中
![image](https://user-images.githubusercontent.com/82516689/128208987-3e39ae15-3c2a-4e4e-b5a3-a71cad929ce4.png)

### 环境
INFO  Yun version 1.6.2. Guide: https://yun.yunyoujun.cn
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19041
node: 14.17.3
v8: 8.4.371.23-node.67
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0

OS: Win10
Browser: Chrome  92.0.4515.107

我是把当前的yun仓库fork了一份，按照submodule的方式给导入我的博客源码的。所作的修改仅限于一些颜色和字体（吐槽一下为啥目录的数字用monospace而目录本身用serif啊...这样的话英文的heading目录视觉效果很不协调；我把他们统一改成serif了）

**Comment by YunYouJun** [comment]
请使用 `types` 而非 `type`。
看起来是部分文档有误，已修复。

**Comment by Reimirno** [comment]
Thx. It's working now.

**Comment by Reimirno** [comment]
Really thank you for the prompt reply. I have another closely-related issue - I know this is really minor but any idea why this happens?
![image](https://user-images.githubusercontent.com/82516689/128219039-f95c69dc-a6df-40e0-b7a1-6da3a0595837.png)
There is a visually pleasing space between the icon and the title text in the case of `zhihu` and `bilibili`, but clearly not in my self-defined `type` which is `steam`. In fact all self-defined `type` will have its icon squeezed up with the title which looks somewhat weird.
The way I import icon is by importing remix icon css at the `head`:
```
head:
  css:
    iconfull: https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css
```
And then I can set the `icon` attribute for my self-defined type like this:
```
types:
  steam:
    color: '#4382aa'
    icon: ri-steam-line
```
It's not about the size of icon because I have tried various size options (`ri-steam-line ri-lg`, `ri-steam-line ri-fw` etc), they doe change the size but all of them would still squeeze the icon and the title together.
![image](https://user-images.githubusercontent.com/82516689/128220147-a6b32571-cc4f-4b08-aa47-523801c1a9df.png)
![image](https://user-images.githubusercontent.com/82516689/128220368-59c646ee-e57b-43af-8d3a-aa093851bcbe.png)

Am I missing anything here? :)

**Comment by YunYouJun** [comment]
This is caused by the css icon, and the theme is used by default as the SVG icon.

We can solve it in two ways.

One:

Use [iconfont](https://www.iconfont.cn/) to custom your icon set.

> https://yun.yunyoujun.cn/about/icon.html#%E9%BB%98%E8%AE%A4%E5%9B%BE%E6%A0%87

Another One:

```yaml
types:
  steam:
    icon: custom-title-icon ri-steam-line
```

Then custom your css and import it in `head` config.

```css
.custom-title-icon {
  margin-right: 0.5rem;
}
```

> Because the spacing and arrangement of different icon sets are different, the theme is optimized only for the default icons.

**Comment by Reimirno** [comment]
THanks! I will definitely try them.
Greatly appreciate your prompt and detailed guidance. Having spent the past few days with Hexo and your theme, I, started from zero experience in front end work, have indeed learnt a lot. Your doc is one of the most detailed I have seen, and your theme's aesthetics is attractive. Great work!
