### ISSUE TITLE
标签不能用 C++ 吗？

### ISSUE THREAD

**Issue by wgx-dh** [YunYouJun/hexo-theme-yun#147]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YunYouJun** [comment]
仔细读文档。

![Uploading image.png…]()

**Comment by wgx-dh** [comment]
标签  tags

**Comment by wgx-dh** [comment]
链接里 C++ 显示不出来  和 C 是一样的

**Comment by YunYouJun** [comment]
自定义。
