### ISSUE TITLE
[Bug Report] 在移动端使用 Valine 回复评论时不能正常添加昵称、邮箱和网址

### ISSUE THREAD

**Issue by leostudiooo** [YunYouJun/hexo-theme-yun#148]
# Bug

## Description
在移动端网页使用 Valine 回复评论时不能正常添加昵称、邮箱和网址。在回复时，点击昵称、邮箱、网址的输入框，但光标会跳到正文输入框。

## Screenshots
![image](https://user-images.githubusercontent.com/35419343/129498524-8a0cf575-d596-4fb9-b3b3-e67347849b27.png)

## Reproduction
打开[我的博客页面](https://leostudiooo.github.io/)，打开任意一篇有评论的文章，对其中任意评论进行回复。

# Dev Info

## PC
- OS:
  - 版本：Windows 11 专业工作站版
  - 版本：21H2
  - 安装日期：‎2021/‎7/‎2
  - 操作系统版本：22000.132
  - 序列号：PF1SQ3XR
  - 体验：Windows 功能体验包 1000.22000.132.0
- Browser:
  - Google Chrome 92.0.4515.131 x64

## Cellphone
- OS: 
  - Android P
- Browser: 
  - Google Chrome 80.0.3987.162

## Repository

https://github.com/leostudiooo/leostudiooo.github.io
Branch: Source

**Comment by YunYouJun** [comment]
Valine 已经基本停止维护状态，不建议使用 Valine，如想要继承数据，可使用类似的 [Waline](https://waline.js.org/)。
