### ISSUE TITLE
Google Analysis不起作用 

### ISSUE THREAD

**Issue by jiabinbin** [YunYouJun/hexo-theme-yun#15]
**Describe the bug**
emm, 我又来了
在我配置google_analytics之后，请求不会成功。
RequestHeaders返回为
Provisional headers are shown
是否为bug?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jiabinbin** [comment]
而且统计并没有生效~

**Comment by YunYouJun** [comment]
可否提供配置代码链接？如 `yun.yml`。

> [谷歌分析](https://yun.yunyoujun.cn/guide/third-party-support.html#%E8%B0%B7%E6%AD%8C%E5%88%86%E6%9E%90)

是否获取正确的 Google Analytics ID ？

**Comment by jiabinbin** [comment]
> 可否提供配置代码链接？如 `yun.yml`。
> 
> > [谷歌分析](https://yun.yunyoujun.cn/guide/third-party-support.html#%E8%B0%B7%E6%AD%8C%E5%88%86%E6%9E%90)
> 
> 是否获取正确的 Google Analytics ID ？

![image](https://user-images.githubusercontent.com/9244703/78873743-eafa6300-7a7d-11ea-8f36-c03d3703d6ad.png)
以上是配置。

**Comment by YunYouJun** [comment]
仅凭该配置无法获取更多错误信息。
可否提供完整的项目代码链接。请检查是否已重新生成部署。是否已强制清楚缓存等。
或进群 389401003 即时反馈交流。

**Comment by jiabinbin** [comment]
好的 thx!

**Comment by jiabinbin** [comment]
补充下原因：
部分chrome广告屏蔽插件会导致这js加载不成功，关掉就行了:(
