### ISSUE TITLE
开启pjax后首页banner文字无法显示

### ISSUE THREAD

**Issue by Adkinsm2020** [YunYouJun/hexo-theme-yun#151]
主题版本号（必须）： v1.6.2
您遇到的问题（必须）： 我遇到了 开启pjax后首页banner文字无法显示 问题。
您期待的结果（必须）：我希望能够解决使用问题。
您所尝试的操作（可选）：我尝试在pjax构造函数的selector中加入"div#banner",但它在某些页面并没有应用pjax.，而是直接请求全部，但banner不显示的问题解决。

**Comment by Adkinsm2020** [comment]
“某些页面”经测试，只有首页产生问题。个人认为可能是div#banner的原因，但不知如何解决

**Comment by Adkinsm2020** [comment]
> “某些页面”经测试，只有首页产生问题。个人认为可能是div#banner的原因，但不知如何解决

从首页进入其他页面（文章、页面）也会出现类似问题

**Comment by Adkinsm2020** [comment]
现在貌似又一切正常

**Comment by YunYouJun** [comment]
可能和你本地的热加载有关系，试试线上是否正常。

**Comment by Adkinsm2020** [comment]
我使用vercel构建，无本地开发过程，线上的问题，有时候出现有时候没有。

**Comment by YunYouJun** [comment]
这反而多半可能是请求发送失败吧。
