### ISSUE TITLE
点击特效无法正常显示

### ISSUE THREAD

**Issue by Adkinsm2020** [YunYouJun/hexo-theme-yun#152]
您需要提供的内容：

- 主题版本号（必须）： v1.6.2
- 您遇到的问题（必须）： 我遇到了 点击特效无法正常显示问题。
  - 截图
![image](https://user-images.githubusercontent.com/75924586/130548285-f6a6fed3-d331-4d10-871b-5bc2916de6a5.png)
刷新后正常，无论是否开启pjax都出现问题。同样也是有时候有有时候没有。

**Comment by Adkinsm2020** [comment]
个人猜测是由于z-index遮盖导致

**Comment by YunYouJun** [comment]
无法复现。控制台 resize 的缘故吧。

**Comment by YunYouJun** [comment]
解决了吗？

**Comment by Adkinsm2020** [comment]
目前已经发现，可能是我打开控制台的原因吧

**Comment by Adkinsm2020** [comment]
具体的原因还未找到

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/a1c87e2d97a70c265f0d2a03f49a8ff89069776a.
