### ISSUE TITLE
LeanCloud 文章统计【pjax】无法显示

### ISSUE THREAD

**Issue by Adkinsm2020** [YunYouJun/hexo-theme-yun#160]
![image](https://user-images.githubusercontent.com/75924586/132080724-555e18f0-a136-4864-bf14-ffc9d2a36763.png)

效果如上。

我开启了pjax，然后开启了访问统计，已手动新建 Counter Class，然后统计正常，但当我开启pjax时，访问统计无法显示（Console无有关Error）。

刷新后即可正常，但pjax的访问没有记录进访问统计。

文章页面和首页展示均有此问题，刷新后均正常。

**Comment by Adkinsm2020** [comment]
浮现地址:blog.adkimsm.asia

**Comment by YunYouJun** [comment]
可以复现，待解决。
