### ISSUE TITLE
aplayer与主题不兼容问题

### ISSUE THREAD

**Issue by kumybryce** [YunYouJun/hexo-theme-yun#17]
**Describe the bug**
使用插件hexo-tag-aplayer后页面的目录失效辽，点击无法切换到对应锚点

**To Reproduce**
1.来到我的一个页面：http://www.kumybryce.work/2020/04/20/hexo/
2.点击侧边栏目录
3.无法跳转

**Expected behavior**
长文章无法跳转要此目录何用

**Screenshots**
![image](https://user-images.githubusercontent.com/54592003/79830550-372b9880-83d8-11ea-9c19-39928edae9ad.png)

**Desktop (please complete the following information):**
- Browser  chrome
- Version  80.0.3987.163

**Additional context**
云游君给康康呀

**Comment by YunYouJun** [comment]
感谢反馈！让我康康。（发现字体意外的粗）
> 有兴趣进群么 389401003，超小声。修好会尽快反馈。

**Comment by YunYouJun** [comment]
Aplayer 问题待解决：Aplayer conflicts with hexo-toc
> https://github.com/MoePlayer/APlayer/issues/242

**Comment by YunYouJun** [comment]
因为 Aplayer 该问题似乎迟迟无法得到解决，现通过 js 实现滚动到指定位置。

fixed: https://github.com/YunYouJun/hexo-theme-yun/commit/9fdcdd9d0e0749a73e502652adef233bd5e713c7

**Comment by hzp2333** [comment]
可以参考https://blog.wangriyu.wang/2018/06-Aplayer.html
