### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-theme-yun#173]
完全按照[文档的这里](https://yun.yunyoujun.cn/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E5%8F%A5)配置的

效果如下图，时而能请求到数据，时而不能，茫然了

![image](https://user-images.githubusercontent.com/38487617/135185198-f50bc571-2acf-43aa-9e6b-be8774c90d23.png)

已查看关闭的 issues

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by YunYouJun** [comment]
是有时候出现，有时候不能是吧，和网络请求有关，可能无解。

**Comment by Brannua** [comment]
> 是有时候出现，有时候不能是吧，和网络请求有关，可能无解。

是滴，好吧
