### ISSUE TITLE
[Feature Request]归档页样式轻微调整了一下，请问可以采纳吗，要不一更新主题就没了。。

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-theme-yun#174]
- 轻微调了一下 archives 页的样式，主要做了：
- 1. 减小大圆点和年份标题大小
- 2. 中间实线改成 1px 虚线
- 3. 本来想让行间距变紧凑些，但是 pc 端有 hover 动画，就没改

- 效果对比图如下（不好意思关公门前耍小刀），但是考虑到主题升级还得自己再改，就麻烦问一下。。

- 感谢大佬！

![image](https://user-images.githubusercontent.com/38487617/135187494-81bfd71b-13eb-4f3c-8495-380498fdc8b8.png)

**Comment by YunYouJun** [comment]
这部分我觉得可能涉及各人偏好问题了。可以通过自定义样式来解决。

外挂 CSS 覆盖即可，无需修改主题源文件，不用担心主题升级问题。

自定义样式见： https://yun.yunyoujun.cn/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F

**Comment by Brannua** [comment]
好嘞！
