### ISSUE TITLE
busuanzi页脚没有显示，但busuanzi链接有返回数据

### ISSUE THREAD

**Issue by Horizon-x** [YunYouJun/hexo-theme-yun#175]
busuanzi页脚没有显示，但busuanzi链接有返回数据。
1.一开始以为是配置问题，最后我把博客根目录下的 source/_data/yun.xml 以及主题目录下的 _config.xml中 busuanzi的配置全部打开，并且确定 _comments.xml中 的 visitor 字段全为 flase；
2.之后百度以为是busuanzi的网址过期问题，但查看了之后发现也不是，已经改成最新的链接地址；
3.最后通过chrome控制台发现 busuanzi 确实返回了信息;

所以，现在我不确定是哪出问题了？希望 YunYouJun 您能帮忙看看。在此，向您表示万分感谢！！！

下面是页面显示：
![](https://z3.ax1x.com/2021/09/30/4IRfNn.png)

博客地址：https://www.onexstone.online

**Comment by YunYouJun** [comment]
能否提供下现在关于 busuanzi 的配置是什么？

**Comment by YunYouJun** [comment]
本地测试可以正常显示。
![image](https://user-images.githubusercontent.com/25154432/135645030-816d4a8f-8f3f-44b1-8fbb-649ad77f1870.png)

**Comment by YunYouJun** [comment]
Your site is currently inaccessible, and I'll close the issue first unless you make sure you can reproduce it.
