### ISSUE TITLE
目前有两个使用问题：1，图片显示不清楚如果点下放大。2，如何给文章设置封面

### ISSUE THREAD

**Issue by caixin-ops** [YunYouJun/hexo-theme-yun#176]
您需要提供的内容：

- 主题版本号（必须）： master分支最新代码
- 您遇到的问题（必须）： 1，图片显示不清楚如果点下放大。2，如何给文章设置封面
  - 线上预览地址49.232.105.26

以下是我的fancybox配置
head:
  css: 
    example: /css/fancybox/jquery.fancybox.min.css
  js: 
    example: /js/fancybox/jquery.fancybox.min.js
    base:
    async:
    defer:
这两个文件我都放到source/下了

**Comment by YunYouJun** [comment]
本主题未集成 `fancybox`，fancybox 使用见官方仓库 https://github.com/fancyapps/fancybox。

**Comment by YunYouJun** [comment]
文章封面这个问题…… 就是主题没有设计封面这个功能，如果您想要在首页文章展示图片，不妨直接插入到摘要里？

**Comment by caixin-ops** [comment]
大佬，我是运维，不太会开发，我按照网上的方法，直接在head添加fancybox的css与js文件加载上了，但是还是没用那功能。咱们这个主题怎么加啊
![image](https://user-images.githubusercontent.com/91619016/135719908-7f4ab351-5493-44d0-bd2a-4b7f3b2be8fa.png)

**Comment by YunYouJun** [comment]
fancybox 还要给 img 标签外包裹 a 标签。

```html
<a data-fancybox="gallery" href="big_1.jpg">
    <img src="small_1.jpg">
</a>

<a data-fancybox="gallery" href="big_2.jpg">
    <img src="small_2.jpg">
</a>
```

再自定义一个外挂的 JS 脚本，插入进入。大致含义是给遍历 document queryselector 查到的 img 标签，给其加个包裹的标签再替换回去就行了。

你大致查一下 dom 元素相关的文档写就行了。

**Comment by Brannua** [comment]
![imgName](imgSrc)

**Comment by caixin-ops** [comment]
意思就是我所有图片都要加标签吗，好不方便啊
