### ISSUE TITLE
[Usage Problem] 大佬的邮箱自动回复具体咋做的呀？

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-theme-yun#177]
您需要提供的内容：

- 主题版本号（必须）： v1.6.3
- 您遇到的问题（必须）： 大佬的邮箱自动回复具体咋做的呀？

**Comment by YunYouJun** [comment]
https://github.com/walinejs/waline

**Comment by Brannua** [comment]
> https://github.com/walinejs/waline

啊我是看过文档才来问的。。抱歉，文档中有的地方说的不是特别清楚
就比如 SMTP_SERVICE 到底填的是哪个值，填入的是纯文本还是需要加引号；
再比如「站点邮箱」「leancloud 邮箱」「serveless 服务平台的邮箱」「头像平台的邮箱」涉及多个平台的邮箱，是否统一，之间什么关系
文档中好像没有特别说明，新手不太清楚，因为我在尝试阶段换了多个邮箱进行设置，现在可能搞乱了。。因为不清楚关系。。所以才来请教大佬您的

**Comment by Brannua** [comment]
我尝试了 163 邮箱和 qq 邮箱，似乎都没有收到邮件提示。。

**Comment by YunYouJun** [comment]
其实邮箱也有点问题，我这边也不是每次都能收到邮件。没有去排查这个。

**Comment by Brannua** [comment]
> 其实邮箱也有点问题，我这边也不是每次都能收到邮件。没有去排查这个。

我丢我是一次也收不到😂
