### ISSUE TITLE
[Bug Report] 评论系统相关

### ISSUE THREAD

**Issue by Adkinsm2020** [YunYouJun/hexo-theme-yun#181]
**Describe the bug**
目前呢，是这个情况。

我目前使用 Waline + Twikoo 双评论，但打开页面时出现了两个评论系统。

原因大概是主题没有检测有几个评论系统，所以都显示了。

图来：

![图片](https://user-images.githubusercontent.com/75924586/136658032-e1f833d5-e155-4b6e-b59c-7f35770bcb9e.png)

目前我的想法是可以在选择之前让两个评论系统都不显示。

**To Reproduce**
文章页面，评论区。

1. Go to <blog.adkimsm.asia>
2. Click on some post button
3. Scroll down to comment

**Expected behavior**
刷新，清缓存，清local storage都没用 ~~（肯定没用啊）~~

控制台无任何error，评论功能正常。

**Screenshots**

![图片](https://user-images.githubusercontent.com/75924586/136658153-ac81a1d1-296e-4a97-b3f6-8768ec228ad1.png)

**Desktop (please complete the following information):**

- OS: windows
- Browser edge with chromium
- Version 94

**Additional context**
希望能够修复（不能修就算了。我自己加个display）

**Comment by Adkinsm2020** [comment]
oh，现在又多了一个bug。

点击 twikoo 按钮切换到第二评论系统一切正常，这是不必说的。

但当点击 waline 按钮时，仍然会出现两个评论系统。

**Comment by YunYouJun** [comment]
这部分的配置是什么？似乎无法复现。

```yml
comment:
  candidates:
```

**Comment by Adkinsm2020** [comment]
https://github.com/adkinsmpage/hexo-blog/blob/master/themes/yun/data/_comments.yml

**Comment by Adkinsm2020** [comment]
目前好像手机端正常，但pc端存在问题

**Comment by Adkinsm2020** [comment]
好像手机端切换到电脑ua后即便在切换回来刷新，也会存在问题
