### ISSUE TITLE
[Usage Problem]大佬的视频资源怎么托管的呀

### ISSUE THREAD

**Issue by Brannua** [YunYouJun/hexo-theme-yun#182]
就是平时我的图片是用 picGo 传到 gitee 上托管的，大佬你是怎么托管视频资源的呀

**Comment by YunYouJun** [comment]
视频资源我托管在了又拍云的云存储。

> 非主题问题可使用 [Discussions](https://github.com/YunYouJun/hexo-theme-yun/discussions)。
