### ISSUE TITLE
自动部署出现错误

### ISSUE THREAD

**Issue by Masle1** [YunYouJun/hexo-theme-yun#196]
- 主题版本号（必须）： v1.6.1
- 您遇到的问题（必须）： 用github action部署的时候，出现了如图的问题。貌似是theme中yun打不开的问题。
- 错误：`Error: fatal: No url found for submodule path 'themes/yun' in .gitmodules
  Error: The process '/usr/bin/git' failed with exit code 128`
  - 截图（可选）
![mmexport1635590224139](https://user-images.githubusercontent.com/80967408/139529874-1506a5df-6f02-4fd1-b3f7-88e4e033a15b.png)
![Screenshot_20211030_183728_com microsoft emmx](https://user-images.githubusercontent.com/80967408/139529908-83a0e32b-5387-4d7b-a3e7-5f3de0f6bdc2.jpg)

- 您期待的结果（必须）：不知道是不是theme/yun的问题，如果是的话希望云游君能提供下解决方案

**Comment by YunYouJun** [comment]
actions 中配置 clone submodules 即可。

https://github.com/YunYouJun/yunyoujun.github.io/blob/79e3dc6fe048ab1f7172aa8b0d26669788b40fb3/.github/workflows/gh-pages.yml#L12
