### ISSUE TITLE
一言插件不稳定

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/hexo-theme-yun#201]
```say.js```大部分情况会一直queuing

<img width="974" alt="Screenshot 2021-11-10 at 8 12 00 PM" src="https://user-images.githubusercontent.com/60996518/141111009-935cf3d3-409f-4db7-853c-817f962776e8.png">

**Comment by YunYouJun** [comment]
120ms 属于正常情况？
关于偶尔不显示问题，已经修复，请切换至 dev 分支最新版。
