### ISSUE TITLE
相册密码和图片地址匹配问题

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/hexo-theme-yun#203]
因为用到本地图片，在本地调试时发现输入密码老出现decrypt error，debug发现程序要求加密相册的第一张图片必须是https格式的，建议在doc中说明。

**Comment by YunYouJun** [comment]
理论上，`https` 还是 `http` 无关，所指本地地址是 `/xxx/xxx` 吗？

**Comment by YunYouJun** [comment]
已添加说明。https://github.com/YunYouJun/hexo-theme-yun/commit/2baf77e0f5df37806bc4f36f9a63c255dd30f078

**Comment by zhoubin-me** [comment]
具体在galley_decrypt.js的这几行
'''javascript
   const testSrc = decrypt(photos[0].dataset.src, password);
    const objExp = new RegExp(
      /http(s)?:\/\/([\w-]+\.)+[\w-]+(\/[\w- .\/?%&=]*)?/
    );
    if (objExp.test(testSrc)) {
'''
objExp 要求匹配http或者https

**Comment by YunYouJun** [comment]
此处通过检测 http 或 https 开头的链接来判断是否解密成功。没有考虑打算使用本地绝对路径的方案。
已修改此部分代码，改为检测是否为 `http` 开头或 `/` 开头。
