### ISSUE TITLE
关于顶部导航栏的建议

### ISSUE THREAD

**Issue by zhoubin-me** [YunYouJun/hexo-theme-yun#205]
虽然顶部导航栏很俗套，但是确实很方便。

每次想跳转页面都要点左上角的菜单，再能点连接，就很麻烦。

建议增加顶部固定导航页面的选项功能。

顶部导航还能有下拉菜单，这样就不怕更多的页面，用侧面导航放不下的问题了。。。

**Comment by zhoubin-me** [comment]
完全不懂前端。。。自己魔改了下。。结果没渲染出来。。。还望能指教一下：

参考butterfly的导航栏，添加如下内容
```layout/_partial/nav.pug```
```
nav#nav
  span#blog_name
    a#site-name(href=url_for('/')) #[=config.title]
    
  #menus
    //- if (theme.algolia_search.enable || theme.local_search.enable)
    //-   #search-button
    //-     a.site-page.social-icon.search
    //-       i.fas.fa-search.fa-fw
    //-       span=' '+_p('search.title')
    !=partial('_partial/menu_item', {}, {cache: true})

    //- #toggle-menu
    //-   a.site-page
    //-     i.fas.fa-bars.fa-fw
```
```
if theme.menu_nav
  .menus_items
    each value, label in theme.menu_nav
      if typeof value !== 'object'
        .menus_item
          - const valueArray = value.split('||')
          a.site-page(href=url_for(trim(valueArray[0])))
            if valueArray[1]
              i.fa-fw(class=trim(valueArray[1]))
            span=' '+label
      else
        .menus_item
          - const labelArray = label.split('||')
          - const hideClass = labelArray[2] && trim(labelArray[2]) === 'hide' ? 'hide' : ''
          a.site-page.group(class=`${hideClass}` href='javascript:void(0);')
            if labelArray[1]
              i.fa-fw(class=trim(labelArray[1]))
            span=' '+ trim(labelArray[0])
            i.fas.fa-chevron-down
          ul.menus_item_child
            each val,lab in value 
              - const valArray = val.split('||')
              li
                a.site-page.child(href=url_for(trim(valArray[0])))
                  if valArray[1]
                    i.fa-fw(class=trim(valArray[1]))
                  span=' '+ lab
```

```css/_variables/nav.styl```
#nav
  position: absolute
  top: 0
  z-index: 90
  display: flex
  align-items: center
  padding: 0 36px
  width: 100%
  height: 60px
  font-size: 1.3em
  opacity: 0
  transition: all .5s

  +maxWidth768()
    padding: 0 16px

  &.show
    opacity: 1

  #blog_name
    flex: 1

  #toggle-menu
    display: none
    padding: 2px 0 0 6px
    vertical-align: top

    &:hover
      color: var(--white)

  a
    color: var(--light-grey)

    &:hover
      color: var(--white)

  #site-name
    text-shadow: 2px 2px 4px rgba($dark-black, .15)
    font-weight: bold
    cursor: pointer

  .menus_items
    display: inline

    .menus_item
      position: relative
      display: inline-block
      padding: 0 0 0 14px

      &:hover
        .menus_item_child
          display: block

        & > a > i:last-child
          transform: rotate(180deg)

      & > a > i:last-child
        padding: 4px
        transition: transform .3s

      .menus_item_child
        position: absolute
        right: 0
        display: none
        margin-top: 8px
        padding: 0
        width: max-content
        background-color: var(--sidebar-bg)
        box-shadow: 0 5px 20px -4px rgba($dark-black, .5)
        animation: sub_menus .3s .1s ease both

        &:before
          position: absolute
          top: -8px
          left: 0
          width: 100%
          height: 20px
          content: ''

        li
          list-style: none

          &:hover
            background: var(--text-bg-hover)

          a
            display: inline-block
            padding: 6px 14px
            width: 100%
            color: var(--font-color) !important
            text-shadow: none !important

  &.hide-menu
    #toggle-menu
      display: inline-block !important

      .site-page
        font-size: inherit

    .menus_items
      display: none

    #search-button span
      display: none

  #search-button
    display: inline
    padding: 0 0 0 14px

  .site-page
    position: relative
    padding-bottom: 6px
    text-shadow: 1px 1px 2px rgba($dark-black, .3)
    font-size: .78em
    cursor: pointer

    &:not(.child)
      &:after
        position: absolute
        bottom: 0
        left: 0
        z-index: -1
        width: 0
        height: 3px
        background-color: lighten($indigo, 30%)
        content: ''
        transition: all .3s ease-in-out

      &:hover
        &:after
          width: 100%

```

最后，在```layout/_partial/layout.pug```的

**Comment by YunYouJun** [comment]
这部分我确实有一定偷懒的因素，所以并没有设计顶部导航栏与展开。此外一个因素则是导航栏确实与现有的首页风格相冲突，会一定程度影响首页的观感，以及我更喜欢使用图标代替页面的导航（博客的页面链接也可以保持在一个相对较少的情况）。
如果实在想添加顶部导航栏，只能拜托自行添加了。
至于你说的没渲染出来，具体是指？

**Comment by zhoubin-me** [comment]
我昨天自己搞了一下。。。感觉效果还可以，移动端会自动不显示，不过我前端code写的稀烂，目前可以在config里面配置menu_nav的enable来选择开启还是关闭。。。顺便倒腾了下banner，欢迎参观指教～

[深水小站](https://zhoubin.me/)

**Comment by YunYouJun** [comment]
定制的很有意思，关于菜单部分，暗色模式下字体颜色可以优化一下。
这部分使用 CSS Var 的话，可以很方便地实现。比如 `color: var(--hty-text-color);`

![image](https://user-images.githubusercontent.com/25154432/141643949-0388f791-89fd-4e95-90b4-ee5a89d9fdb2.png)

**Comment by zhoubin-me** [comment]
还有就是我的文章和归档页突然有边框，就变窄了，不好看，我猜测应该是我用的bootstrap nav bar引入的css跟主题产生冲突了，我网上搜的用bootstrap iso，加div分隔就不管用。。还望指教

**Comment by YunYouJun** [comment]
边框没大明白所指的是什么，能否截图示意？

**Comment by zhoubin-me** [comment]
正常文章宽度是这样
<img width="1346" alt="Screenshot 2021-11-13 at 8 49 58 PM" src="https://user-images.githubusercontent.com/60996518/141644477-f6f6aeb6-4b32-4351-a593-8c57ce8a568f.png">

引入bootstrap的css后变成了这样
<img width="1346" alt="Screenshot 2021-11-13 at 8 50 21 PM" src="https://user-images.githubusercontent.com/60996518/141644492-b0f56767-3b73-4fd5-84d5-c1ebed7e68eb.png">

**Comment by zhoubin-me** [comment]
注释掉引入的bootstrap css就okay了

还有公式颜色可以调成跟文字一样的颜色么，暗色主题公式就不好看了

**Comment by YunYouJun** [comment]
> 注释掉引入的bootstrap css就okay了，但是导航栏就不行了，现在确定是boostrap的css跟主题的冲突的问题了
> 
> 还有公式颜色可以调成跟文字一样的颜色么，暗色主题公式就不好看了

公式颜色是由于后来 blockquote 引入的 class 与 katex 生成的 `base` 名冲突了，导致了覆盖。
现已修复。与文字颜色保持一致。
