### ISSUE TITLE
dplayer 播放器 全屏有黑边框

### ISSUE THREAD

**Issue by wgx-dh** [YunYouJun/hexo-theme-yun#208]
![image](https://user-images.githubusercontent.com/63238251/142610611-b3d98132-449a-4a34-84d6-1bcec2abc40a.png)

上两个版本的主题还没有这个问题。

https://cuffs.cf/posts/hsbdla/

 Chrome 火狐 Edge 测试了都这样

**Comment by YunYouJun** [comment]
播放器全屏有边框和主题没关系吧。Dplayer 样式更新了？主题并没有内嵌 Dplayer。

**Comment by wgx-dh** [comment]
我用  1.5.0 的主题 就没问题 
是不是 你们的 css 冲突了

**Comment by wgx-dh** [comment]
我找到了
![image](https://user-images.githubusercontent.com/63238251/142648339-9a5aa849-4557-4191-896f-ed319a5fd764.png)
