### ISSUE TITLE
[Bug Report]主题文档在英语界面的问题

### ISSUE THREAD

**Issue by lfhsheng** [YunYouJun/hexo-theme-yun#209]
在主题文档的[英语界面](https://yun.yunyoujun.cn/en/)，无法显示`快速上手`按钮（应该是你没加上去吧）😶‍🌫️

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/b30319c961c624cb138d279aeea0cb9a0ea8b593.
