### ISSUE TITLE
toc点击标题无法跳转

### ISSUE THREAD

**Issue by yuzijiangorz** [YunYouJun/hexo-theme-yun#21]
![](https://s1.ax1x.com/2020/04/26/JcUQ2V.jpg)

可以看到，地址栏上的已经到了“快速幂”

而显示的仍然是“大数字”

没有开applayer

**Comment by YunYouJun** [comment]
希望提 ISSUE 时可以提供可复现的在线链接……

**Comment by yuzijiangorz** [comment]
。。。

https://ws28.cn/f/2dr2ft7ex5z

**Comment by YunYouJun** [comment]
太大了，我不能每次都下载你的文件重新跑……这只是实在没有别的方法时的最终手段。
用一下 git，然后 `.gitignore` 掉 `node_modules`。或者提供线上可访问的文章链接以评估。

**Comment by yuzijiangorz** [comment]
谢谢博主,close掉吧。我BFS一下
