### ISSUE TITLE
webpusher引入的js报错

### ISSUE THREAD

**Issue by Masle1** [YunYouJun/hexo-theme-yun#217]
我在配置webpusher后，发现一直没有运行。
看见控制台报了这个错
![1639896876(1)](https://user-images.githubusercontent.com/80967408/146666644-ca048c23-15fd-4c9d-a337-18daa3fe91f7.png)
试了其他主题，发现其他主题配置后很正常，如下图
![1639897100(1)](https://user-images.githubusercontent.com/80967408/146666705-cf4467f1-6720-4757-a848-64f62a13622f.png)

这个app.min.js的链接是https://cdn.webpushr.com/app.min.js

复现可以去https://masle.top  看看,或者云游君自己试试

**Comment by YunYouJun** [comment]
主题应该没有提供 Webpush 的配置。（所以这个应该和主题无关吧）

**Comment by Masle1** [comment]
> 主题应该没有提供 Webpush 的配置。（所以这个应该和主题无关吧）

主要是我发现其他主题使用起来都是正常的，但是换成yun就不行了。怀疑会不会是和主题哪里冲突还是其他原因

**Comment by YunYouJun** [comment]
`today` 变量名冲突所导致。

Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/5bae240d34ca42f3fd82c911db0edf80baeb1e7f.
