### ISSUE TITLE
[Bug Report]更改关于jsDelivr CDN的说明文档

### ISSUE THREAD

**Issue by Lfhsheng** [YunYouJun/hexo-theme-yun#219]
如题，众所周知jsDelivr CDN出了问题，但在[文档](https://yun.yunyoujun.cn/guide/config.html#cdn)里再介绍它就不合适了😶

**Comment by YunYouJun** [comment]
jsDelivr 似乎已恢复使用，大陆地区将会解析到香港附近，且除此之外并无其他国内可替代 CDN，只能仍旧使用 jsDelivr。

**Comment by lfhsheng** [comment]
又拍云倒是挺好的，只不过要备案才能用🤡

**Comment by YunYouJun** [comment]
目前就通用性来说，国内还是缺乏 jsDelivr 的替代品，所以决定还是维持原样。
