### ISSUE TITLE
救救孩子之代码高亮

### ISSUE THREAD

**Issue by chenlvtang** [YunYouJun/hexo-theme-yun#22]
**Describe the bug**
博客代码高亮有问题，前前后后弄了两次，但是我实在是逊啦，云游君能不能帮我康康。

**To Reproduce**
首先，我按照了文档进行配置,如图一所示。
接着，我写下了图二所示的代码块。
结果我上传的时候是如图三所示(之前我以为是我的hexo-inject,然后我把他卸载了,结果还是一样)。
F12是图四这个亚子。

**Expected behavior**
我以为他会和你们的一样很美的。

**Screenshots**
图一：
![image](https://user-images.githubusercontent.com/56435336/80494401-36c36c80-8999-11ea-83b8-6331bd3cc37e.png)
图二:
![image](https://user-images.githubusercontent.com/56435336/80494952-daad1800-8999-11ea-9051-97f635ee3c9a.png)
图三:
![image](https://user-images.githubusercontent.com/56435336/80495065-016b4e80-899a-11ea-98bb-4029631279dd.png)
图四：
![image](https://user-images.githubusercontent.com/56435336/80495232-40999f80-899a-11ea-9bb6-75d353aa13a8.png)
图五：
![image](https://user-images.githubusercontent.com/56435336/80496196-6ecbaf00-899b-11ea-9681-b472e1659a93.png)

**Desktop (please complete the following information):**

- OS: [windows 10]
- Browser [chrome]
- Version [lastest]

**Additional context**
没有高亮实在是难受，嘤嘤嘤。
（我的hexo渲染器换了，现在是”hexo-renderer-markdown-it“，安装"hexo-prism-plugin的过程中有 
  图五所示的信息，但因为我实在是太菜，看不懂....."）

**Comment by YunYouJun** [comment]
看起来只是单纯的 `html` 代码被渲染成真正的 html 了吧。

可否提供线上代码链接？

或者检查下你的代码是否使用正确的方式包裹。
如：

markdown 中：

![image](https://user-images.githubusercontent.com/25154432/80497425-054ca000-899d-11ea-882d-2b8f5a11303f.png)

实际效果：

```html
<img src="#">
```

**Comment by YunYouJun** [comment]
懂了，尝试了 `hexo-renderer-markdown-it` 后的确会出现这个问题。该渲染器没有对代码进行转译，所以标签会被当作正常的 `html` 标签渲染。
建议直接使用 `hexo-renderer-marked`（会将标签进行转译），可以正常显示。

> 卸载 `hexo-renderer-markdown-it` 重新安装 `hexo-renderer-marked` 时，记得 `hexo clean`。

**Comment by chenlvtang** [comment]
谢谢云游君。
当初更换渲染器是因为要渲染emoji😄，不知道换回去之后我的emoji还有用吗。
明天我试试。👌

**Comment by YunYouJun** [comment]
emoji 没啥问题吧，我随便测试了下。如图：

![image](https://user-images.githubusercontent.com/25154432/80500232-835e7600-89a0-11ea-85fe-301c9cd848cc.png)

**Comment by chenlvtang** [comment]
***换回了原渲染器，成功实现代码高亮，谢谢云游君，但是emoji没用了***
之前是看了类似于这篇的文章（https://www.geek-space.cn/post/emoji.html#more）所以换了渲染器。

用输入法输入的emoji有用，如图：
![image](https://user-images.githubusercontent.com/56435336/80551870-833d9500-89f7-11ea-90c9-6bae2a0e7025.png)
但是在Typora中用编码输入的emoji没用了，如图：
![image](https://user-images.githubusercontent.com/56435336/80551907-9cdedc80-89f7-11ea-964f-55e004abd551.png)
之前的渲染可以渲染emoji：
![image](https://user-images.githubusercontent.com/56435336/80551983-d6afe300-89f7-11ea-9a4e-991df997258c.png)

云游君是采取什么方式实现的emoji呢。
（ps：刚刚发现之前那个渲染器的目录不能跳转，之前我还以为就是这样的呢，哈哈哈，看来大家不要随便换东西。）

**Comment by YunYouJun** [comment]
其实只是单纯想输入 emoji 的话没有必要使用 `:baby:` 的形式。这是 `markdown-it` 的插件将 emoji 字符名渲染为了 emoji。实际上你完全可以直接输入 emoji 符号，省去用字符转译这一步。

> 譬如这是一个 emoji 名称与图形的对应网站。
> https://emoji.js.org/

emoji 的显示效果实际上只和你的系统或者浏览器有关。

**Comment by chenlvtang** [comment]
哈哈，刚刚才发现win+。可以快速的输入emoji。（这个chenlvtang就是逊啦）
嘤嘤嘤，我又发现一个事，不知道云游君有没有这个问题。
**当选择使用两种风格的代码块的时候也会渲染失败**
![image](https://user-images.githubusercontent.com/56435336/80552670-f3e5b100-89f9-11ea-893a-e550108bf47f.png)
![)GLZ{J5BIVNMO9X1BE2(PRA](https://user-images.githubusercontent.com/56435336/80552680-f9db9200-89f9-11ea-9f1d-885cd492a5aa.png)
![4D@LT4@13%J$_I}73333RZQ](https://user-images.githubusercontent.com/56435336/80552683-fcd68280-89f9-11ea-95f6-fe379ebffb14.png)
**单独选择一种语言是没事的**
![image](https://user-images.githubusercontent.com/56435336/80553502-aa4a9580-89fc-11ea-94bc-6612960592c7.png)

**Comment by YunYouJun** [comment]
实际上我从来不知道有同时设置两种语言的用法……
只设置一种语言足矣，你想文件的后缀名从来都只有一个啊。

**Comment by chenlvtang** [comment]
哈哈 但是Typora可以喂，行吧。 
就这样吧，谢谢云游君，打扰了，我Close了哦。
