### ISSUE TITLE
关于更改示例站点的建议

### ISSUE THREAD

**Issue by lfhsheng** [YunYouJun/hexo-theme-yun#220]
我是不只一点的好奇[无锡欣跃不锈钢有限公司](https://wxxybxg.bsblog.cn/)是什么鬼玩意？
商业推广？
你选错人了！
强烈建议删除😡

**Comment by YunYouJun** [comment]
该站点非商业推广，只是其不存在违法信息，也确实使用了本主题。因此符合申请示例站点的条件。

（众生平等）

> 还有就是我觉得放进去很搞笑
