### ISSUE TITLE
[Bug Report]疑似文档的样式加载失败

### ISSUE THREAD

**Issue by lfhsheng** [YunYouJun/hexo-theme-yun#228]
![Microsoft Edge](https://user-images.githubusercontent.com/74490140/147823216-b4d9f59d-3782-4e13-b71f-0ba8adfbdf32.png)

![Google Chrome](https://user-images.githubusercontent.com/74490140/147823284-7d7dad16-785b-42ed-81f5-46590648d26c.png)

也可能是我用了科学上网的原因， @YunYouJun 可以试一试

- Microsoft Edge 96.0.1054.62
- Google Chrome 94.0.4606.81

**Comment by Big-Cake-jpg** [comment]
+1

**Comment by lfhsheng** [comment]
没有用科学的手机也是如此，看来是出问题了

**Comment by YunYouJun** [comment]
I will fix it as soon as possible.

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/a9a45e89efaa8ab0a7e8659993776bd769771d8b.
