### ISSUE TITLE
有个小问题，为啥我的girls显示不出来呢

### ISSUE THREAD

**Issue by NaiveSakura** [YunYouJun/hexo-theme-yun#23]

**Comment by YunYouJun** [comment]
参见文档：[页面配置](https://yun.yunyoujun.cn/guide/page.html#%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE)
![image](https://user-images.githubusercontent.com/25154432/80580425-17324f80-8a3e-11ea-9251-c850a14437cb.png)

这么设计的原因是你可以开启 Girls 页，并自由决定是否将其放入导航链接，或放置于它处。

**Comment by YunYouJun** [comment]
如果你觉得问题已得到解决，请在看到该回复后关闭该 ISSUE。

**Comment by NaiveSakura** [comment]
> _No description provided._
