### ISSUE TITLE
[Feature Request]希望可以增加Artitalk选项

### ISSUE THREAD

**Issue by Lfhsheng** [YunYouJun/hexo-theme-yun#238]
我按照[Artitalk官网](https://artitalk.js.org)进行配置

```html
<!-- 引用 artitalk -->
<script type="text/javascript" src="https://unpkg.com/artitalk"></script>
<!-- 存放说说的容器 -->
<div id="artitalk_main"></div>
<script>
new Artitalk({
    appId: '', // Your LeanCloud appId
    appKey: '' // Your LeanCloud appKey
})
</script>
```

然后就变成了这个鬼样子

https://blog.lfhsheng.top/artitalk

希望可以在`yaml`配置文件中增加关于`Artitalk`的选项

（在[官网](https://yun.yunyoujun.cn)中没有找到配置`Artitalk`的选项）

（可能是我瞎了找不到（搜索引擎坏了），另：为什么目录只能展开2级标题，3、4级标题就展不开了？）

**Comment by YunYouJun** [comment]
子目录展开问题已修复。

搜索问题是 Algolia DocSearch 服务迁移了，暂时还没找到新的解决方案。

**Comment by Lfhsheng** [comment]
`hexo-theme-yun`对`Artitalk`的兼容性不太好，缩放比例有些奇葩

- [ ] 在主题里新建一个`Artitalk`的选项

**Comment by Adkinsm2020** [comment]
短博文可以使用HexoPlusPlus提供的talk，目前我博客正常

**Comment by YunYouJun** [comment]
在查看了 `Artitalk` 的功能后，我觉得它的功能与微博 / Twitter 重合，且需要额外配置 LeanCloud。
以及考虑到上传图片的便捷，因为我认为使用现有的社交平台要更为合适，暂不考虑内置该功能。
可以用户自定义样式。
