### ISSUE TITLE
[Bug Report] img标签中设置的尺寸无效

### ISSUE THREAD

**Issue by cloudfox2** [YunYouJun/hexo-theme-yun#239]
从0.7.0更新到1.7.0之后，正文中img标签中设置的尺寸就无效了，不管是设成百分比还是固定值，都显示原始大小，之前是有效的

`<img align="right" src="https://cf0.oss-cn-shanghai.aliyuncs.com/img/Lenna.jpg" height="33%" width="33%"/>`

![showcase](https://s2.loli.net/2022/01/13/hcw1ZQGXN6OSUfv.png)

**Comment by YunYouJun** [comment]
是否有可复现地址？我试一下。

**Comment by YunYouJun** [comment]
明白了，将稍后修复。

**Comment by YunYouJun** [comment]
已修复。

**Comment by cloudfox2** [comment]
还有个问题之前没注意到，align到两边的图片会有条白边

**Comment by YunYouJun** [comment]
> 还有个问题之前没注意到，align到两边的图片会有条白边

现在自定义宽度还会有吗？

**Comment by cloudfox2** [comment]
> > 还有个问题之前没注意到，align 到两边的图片会有条白边
> 
> 现在自定义宽度还会有吗？

还有，不自定义宽度也有

**Comment by YunYouJun** [comment]
> 还有，不自定义宽度也有

已修复。https://github.com/YunYouJun/hexo-theme-yun/commit/6e790c18ec3a5e4f191ef9e8b532ce7989d94e8d
