### ISSUE TITLE
[Feature Request]为Yun增加首页菜单

### ISSUE THREAD

**Issue by Lfhsheng** [YunYouJun/hexo-theme-yun#243]
主题做的挺好的
但有个比较困扰我的点就是我没办法建一个专栏，有些文章直接放`_post`里就显得很杂乱无章
我认为可以在首页增加一个菜单栏
像[hexo-theme-butterfly](https://github.com/jerryc127/hexo-theme-butterfly)一样
![2022-01-20-20-00-40](https://user-images.githubusercontent.com/74490140/150335098-4c0ccb32-5993-4bb6-9c11-b7c14a1400ba.png)
![2022-01-20-20-00-57](https://user-images.githubusercontent.com/74490140/150335104-b8eea054-f7cf-4086-8104-df6dd4e995fe.png)
这样的话就可以比较清晰的整理文章
~~期待`1.8.0`哦😘~~

**Comment by YunYouJun** [comment]
专栏是啥样……

可以用 categories 和 tags 管理。

**Comment by Lfhsheng** [comment]
但是一般人都没有这个习惯😟

**Comment by Lfhsheng** [comment]
毕竟不是每个人都会有这样的习惯

**Comment by Lfhsheng** [comment]
希望能整个像上面那样子的
同时感觉不会和侧边栏重复

**Comment by Lfhsheng** [comment]
或者搞成二选一的

**Comment by YunYouJun** [comment]
感觉破坏现有设计了……

**Comment by Lfhsheng** [comment]
不然就把这玩意搞到左边

**Comment by Lfhsheng** [comment]
或者搞在右边，样式像书签一样的

**Comment by Lfhsheng** [comment]
把受众不同的东西搞在一起会很乱

**Comment by YunYouJun** [comment]
可以在左侧下方自定义图标，链接定向到对应 categories 就行了。

**Comment by Lfhsheng** [comment]
貌似可行
