### ISSUE TITLE
使用Aplayer时，head头部资源出现异常

### ISSUE THREAD

**Issue by Mr-metasequoia** [YunYouJun/hexo-theme-yun#251]
您需要提供的内容：

- 主题版本号（必须）： v1.7.0
- 您遇到的问题（必须）： 

我有两个css文件通常可以被正常加载。
![image](https://user-images.githubusercontent.com/76619254/151103837-a584c755-5291-450d-bd09-027359fd2a2c.png)
后来，我想使用全局音乐播放器，添加了相应的配置
![image](https://user-images.githubusercontent.com/76619254/151104105-61a2d99b-d94b-4717-b227-1cead095360a.png)
我在 Hexo 的根目录下的 _config.yml 中，也添加了相应的配置
![image](https://user-images.githubusercontent.com/76619254/151104259-8d5bd06f-1ea0-4168-b65f-a86cbf82eeca.png)

最后我执行hexo g渲染，却出现了如下所示的问题。
![image](https://user-images.githubusercontent.com/76619254/151104379-8483cba6-f0c1-4241-8daf-9d0a5bfe12fe.png)
![image](https://user-images.githubusercontent.com/76619254/151104410-4a850774-03a9-40ea-b855-f6f51c6205c3.png)
**即在生成的public/css文件夹中，原本正常的各个css文件被加入了link和script标签。**

匪夷所思。
我现在靠在部署前，**手动删除css文件里的这些不合法标签**，姑且可以使用。但还是希望有更好的办法。
云游大老师！请指导我！我什么都会做的（雾
  
- 您期待的结果（必须）：我希望hexo g操作后，不再有奇怪的link和script标签出现在css文件里。

**Comment by Mr-metasequoia** [comment]
另外，我还发现使用Aplayer之后，首页的“一言”又不显示了。
包括全局播放器和单一页面的播放器，只要加入任何一个都将不显示一言。
不知道是出了什么问题？

**Comment by YunYouJun** [comment]
这是 Aplayer 的问题。

需关闭 Aplayer 的自动脚本插入：

```yaml
aplayer:
  asset_inject: false
```

> 可参见 https://yun.yunyoujun.cn/guide/additional-package-support.html#%E6%92%AD%E6%94%BE%E5%99%A8

**Comment by Mr-metasequoia** [comment]
> 这是 Aplayer 的问题。
> 
> 需关闭 Aplayer 的自动脚本插入：
> 
> ```yaml
> aplayer:
>   asset_inject: false
> ```
> 
> > 可参见 https://yun.yunyoujun.cn/guide/additional-package-support.html#%E6%92%AD%E6%94%BE%E5%99%A8

问题解决了，谢谢云游君。有看到这个tip，但没想到该在这里改，我自裁OTZ
