### ISSUE TITLE
[Feature Request] 代码折叠

### ISSUE THREAD

**Issue by Sarofc** [YunYouJun/hexo-theme-yun#253]
希望可以加一个代码折叠功能

主题很好看😊

**Comment by YunYouJun** [comment]
能否更详细地描述该功能内容？

**Comment by Sarofc** [comment]
需求是，有的代码片比较长，想只显示一部分（点击显示全部/或者可以滑动），或者可以被折叠起来

使用下面的代码来实现折叠，也可以实现需求

<details>
<summary>Example Label</summary>
code
</details>
