### ISSUE TITLE
不蒜子显示问题

### ISSUE THREAD

**Issue by QianChenJun** [YunYouJun/hexo-theme-yun#254]
您需要提供的内容：

- 主题版本号（必须）： v1.7.0
- 您遇到的问题（必须）：卜算子总是加上display：none的效果
  - 截图（可选）
![image](https://user-images.githubusercontent.com/74245184/153178396-03d859db-edff-4750-bd33-e9cb1f24f42c.png)

  - 代码仓库（可选）
  - 线上预览地址（可选）https://www.qianchen.xyz/

您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by YunYouJun** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/25154432/153186573-5982e36a-35d4-434d-9f9d-70dd72879861.png">

查看是可以正常显示的，请检查是否因为广告屏蔽插件等引起的问题。

**Comment by QianChenJun** [comment]
好的, 刚才我使用chrome浏览器查看没有问题
图为edge浏览器。
（￣︶￣）↗

**Comment by QianChenJun** [comment]
![image](https://user-images.githubusercontent.com/74245184/153190048-b5f2d68d-a734-4e4b-a66b-0cc30292cc71.png)
当我多次刷新网页的时候 就会多出来一个element.style 添加的样式
关闭了广告屏蔽插件也是如此

**Comment by QianChenJun** [comment]
找到问题所在了，是跟live2d起了冲突
( •̀ ω •́ )✧
