### ISSUE TITLE
修改Hexo博客文章，怎么自动更新文章时间？updated:xxx

### ISSUE THREAD

**Issue by hqw567** [YunYouJun/hexo-theme-yun#255]
您需要提供的内容：
 v1.8.8
 我遇到了 文章更新 问题。
 
![image](https://user-images.githubusercontent.com/74847198/153422477-5288ebd6-a969-428d-8b5f-3c45360cc4c2.png)
我希望能够得到 更新文章自动修改updated时间 结果。

@YunYouJun

**Comment by YunYouJun** [comment]
现在存在的问题是？

**Comment by hqw567** [comment]
更新博客，updated时间随更新变为当前更新的时间，

现在文章updated时间是要自己加，自己改

**Comment by hqw567** [comment]
![image](https://user-images.githubusercontent.com/74847198/153528268-5312fe1f-bc6f-4afc-bf45-9d1df813bd0a.png)
