### ISSUE TITLE
[Bug Report] 最新版本开启 pjax 后 Waline 的 SPA 支持失效

### ISSUE THREAD

**Issue by Big-Cake-jpg** [YunYouJun/hexo-theme-yun#256]
**Describe the bug**
在更新了 Yun 1.8.x 版本以后，自己博客里的 Waline 就无法在开启 pjax 的情况下在文章内加载，除非刷新

**To Reproduce**

1. 打开 <https://bigcake.cakemc.top>
2. 打开任意文章或者「关于我」
3. 翻到最底下

**Expected behavior**
以前的 Yun 版本 Waline 都是正常加载的，只有更新到 1.8.x 版本以后变成了这样

**Screenshots**
刷新前：
![image](https://user-images.githubusercontent.com/76810494/153544442-8c210a0c-1cd5-4b4d-ad00-78ef6e48e43b.png)
刷新后：
![image](https://user-images.githubusercontent.com/76810494/153544517-02ed546a-7a2c-46f8-859e-7e4634f6f28e.png)

**Desktop (please complete the following information):**

- OS: Windows Server 2012 R2
- Browser: Microsoft Edge
- Version: 98.0.1108.43

**Smartphone (please complete the following information):**

- Device: iPhone 6 Plus
- OS: iOS 12.5.5
- Browser: Safari
- Version: 537.36

**Comment by YunYouJun** [comment]
将会尽快修复。

**Comment by Big-Cake-jpg** [comment]
> 将会尽快修复。

还有些其它问题，页面的部分配置在完成静态页面生成以后，有主题默认设置的，也有在配置文件`_config.yun.yml`里配置的

**Comment by YunYouJun** [comment]
> 还有些其它问题，页面的部分配置在完成静态页面生成以后，有主题默认设置的，也有在配置文件_config.yun.yml里配置的（比如评论区上面的那几句话，还有鼠标点击的烟花效果）

没怎么看懂，可以截图示意吗？

**Comment by Big-Cake-jpg** [comment]
> > 还有些其它问题，页面的部分配置在完成静态页面生成以后，有主题默认设置的，也有在配置文件_config.yun.yml里配置的（比如评论区上面的那几句话，还有鼠标点击的烟花效果）
> 
> 
> 
> 没怎么看懂，可以截图示意吗？

![image](https://user-images.githubusercontent.com/76810494/153823170-854aa004-d40b-47aa-a064-f3ac07182da4.jpeg)

![image](https://user-images.githubusercontent.com/76810494/153823223-61ec74c0-235d-46ea-9d24-c738b6be3a98.jpeg)

**Comment by Big-Cake-jpg** [comment]
> 希望的烟花颜色是？

我的[主题设置](https://github.com/Big-Cake-jpg/big-cake-jpg.github.io/blob/source/_config.yun.yml)里的那几种颜色

```
fireworks:
  enable: true
  colors:
    - "115, 75, 52"
    - "242, 188, 87"
    - "242, 205, 94"
    - "242, 242, 242"
```

**Comment by YunYouJun** [comment]
烟花颜色问题已修复，等 Waline 修复发新版本。
