### ISSUE TITLE
首页标语动不能显示[Bug Report]

### ISSUE THREAD

**Issue by MuYaoNanzhi** [YunYouJun/hexo-theme-yun#259]
版本v1.8.8首页标语动画没有显示

**Comment by YunYouJun** [comment]
能否截图/录屏？
我也是 v1.8.8，但是无法复现。

**Comment by MuYaoNanzhi** [comment]
![1645449765(1)](https://user-images.githubusercontent.com/95462324/154963645-fd85e927-9421-4c97-8078-ed6a957e0f2c.png)



是这样的，侧边栏也点击不出来

**Comment by YunYouJun** [comment]
开启了 PJAX？Hexo 版本是否大于 5.2.0？是否使用 npm 安装？

信息太少，没法排查。

**Comment by MuYaoNanzhi** [comment]
没有开启pjax，hexo版本是5.4.1，使用的是npm安装

**Comment by YunYouJun** [comment]
在线链接或代码？无法复现。

**Comment by MuYaoNanzhi** [comment]
blog.xsgymq.com

**Comment by MuYaoNanzhi** [comment]
原先的 themes/yun 文件夹是删除了的，然后，是不是需要把默认主题landscape删除呢？那需要我怎么删除呢？

**Comment by YunYouJun** [comment]
我认为该问题已得到解决。
