### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by yuzijiangorz** [YunYouJun/hexo-theme-yun#26]
请问hexo-theme-yun的valine是通过什么方式来实现的呢

是用的CDN吗？如果是的话，麻烦告诉我在哪里引用的好吗？

如果用的是其他的话可不可以告诉我valine.min.js的位置呢？

你的valine.pug让我感觉我用了个寂寞

谢谢了

**Comment by yuzijiangorz** [comment]
想加入更多表情

**Comment by YunYouJun** [comment]
正所谓 `云`，本项目所用的第三方基本全部使用 cdn 引入的方式，以减小本体大小，提高访问速度。
valine.pug 很简洁优雅不是么。

CDN 引入见 https://github.com/YunYouJun/hexo-theme-yun/blob/946665cbcd09261d675762a6122feec96d521c74/_config.yml#L280

config 配置见：https://github.com/YunYouJun/hexo-theme-yun/blob/946665cbcd09261d675762a6122feec96d521c74/_config.yml#L523-L526

> 请在 `yun.yml` 中配置。

v0.7.0 之前的版本配置在 `scripts/helpers/yun-config.js` 中，v0.7.0 已移动至 `valine-visitor.pug` 中。

**Comment by yuzijiangorz** [comment]
谢谢
