### ISSUE TITLE
[Bug Report] 空的preload会被渲染为undefined

### ISSUE THREAD

**Issue by MoetaYuko** [YunYouJun/hexo-theme-yun#262]
**Describe the bug**
默认preload中script为空，https://github.com/YunYouJun/hexo-theme-yun/blob/bc9b50a839c729e32512213da3f1788cce4d5a36/_config.yml#L229-L232
渲染结果为
```html
<link rel="preload" href="/undefined" as="script"><link rel="preload" href="/css/hexo-theme-yun.css" as="style">
````

**Expected behavior**
没有script

**Desktop (please complete the following information):**

- OS: Arch Linux
- Browser: chrome
- Version: 98.0.4758.102

**Comment by YunYouJun** [comment]
感谢反馈。Fixed and Released in `v1.8.11`.
