### ISSUE TITLE
[Feature Request]为主题提供Cravatar支持

### ISSUE THREAD

**Issue by okatu-loli** [YunYouJun/hexo-theme-yun#266]
因为Gravatar在国内的访问速度不是很理想，而国内的[Cravatar](https://cravatar.cn/)项目完全支持Gravatar的结构，所以希望能提供一个选项来让用户决定使用Gravatar还是Cravatar

**Comment by YunYouJun** [comment]
是不是发错仓库了？本项目似乎并没有使用 Gravatar。

**Comment by YunYouJun** [comment]
本主题与 Gravatar 并无直接关联，我将关闭该 Issue。
