### ISSUE TITLE
[Feature Request] 希望支持截取文章内容生成摘要

### ISSUE THREAD

**Issue by AkaraChen** [YunYouJun/hexo-theme-yun#271]
我写文章的时候不太喜欢写前言之类的东西，因此 `<!--more-->` 加在哪里都不太合适，而且我也没有 pug 模板引擎的使用经验，所以只能求作者适配了（）

**Comment by YunYouJun** [comment]
实现的话倒是并不麻烦，但是截断的位置很难把握，如果自动截取固定长度的话，可能会导致在不希望的地方进行截断。
使用 `<!--more-->` 总是更优雅的。
