### ISSUE TITLE
请问怎么支持 gif 图？

### ISSUE THREAD

**Issue by zeqinjie** [YunYouJun/hexo-theme-yun#274]
markdown 书写，用 github 查阅是正常，但自己博客就不正常

**Comment by YunYouJun** [comment]
Example?

**Comment by zeqinjie** [comment]
https://github.com/zeqinjie/blog/blob/master/source/_posts/%E4%BA%8C%EF%BC%89Flutter-%E5%8A%A8%E7%94%BB%E8%AF%A6%E8%A7%A3%EF%BC%88%E4%B8%80%EF%BC%89.md

**Comment by zeqinjie** [comment]
> GitHub 图片链接错误，该路径仅为 GitHub 使用，想作为外链请使用 `raw.githubusercontent.com`（请自行搜索）。

好的谢谢~
