### ISSUE TITLE
按照文档安装完以后运行报错

### ISSUE THREAD

**Issue by xiaoyuebao** [YunYouJun/hexo-theme-yun#275]
按照文档步骤安装
npm install hexo-theme-yun@latest
npm install hexo-render-pug hexo-renderer-stylus
_config.yml 主题 也改了，但是运行起来以后显示空白页，控制台报WARN  No layout: index.html，
用以前的clone方法就没问题，但是npm方式不行，百度出来的都是clone方式，没有npm方式的，请问这个问题怎么解决

**Comment by YunYouJun** [comment]
删除 themes 文件夹试试。

**Comment by YunYouJun** [comment]
请提供可复现示例。

**Comment by xiaoyuebao** [comment]
这是问题项目地址https://github.com/xiaoyuebao/blog.git
![image](https://user-images.githubusercontent.com/21011265/160736922-bf6b8665-71d9-4290-8967-05d6eb526ac9.png)

**Comment by YunYouJun** [comment]
![96AF4DAB534F7BCF9ED12D9F1DE386F6](https://user-images.githubusercontent.com/25154432/160808306-f17c9152-9cf4-4702-a0f4-16668d07235b.gif)

你这没装主题啊……

<img width="492" alt="image" src="https://user-images.githubusercontent.com/25154432/160808164-3b9b7442-80cb-4c35-a4fd-4e76b3cac21d.png">

**Comment by xiaoyuebao** [comment]
是这样的，我先执行npm install hexo-theme-yun@latest，运行起来以后打开是这样的
![image](https://user-images.githubusercontent.com/21011265/160834711-4b79f6cc-1f93-4002-9492-345dcef6d0bf.png)
node_modules里也有yun主题文件夹
![image](https://user-images.githubusercontent.com/21011265/160834910-80dd59b2-cd3f-40f8-9b40-e9f9f83f3a5e.png)，
所以我就执行了npm install hexo-render-pug hexo-renderer-stylus
然后node_modules里yun主题文件夹就没了，然后多了个hexo-render-pug
![image](https://user-images.githubusercontent.com/21011265/160835507-c7b40f1e-be08-4399-a7ea-fd97aa19b106.png)，
然后就出现了我说的no layout问题，但是当我再次安装yun主题，hexo-render-pug就没了，打开页面还是
![image](https://user-images.githubusercontent.com/21011265/160834711-4b79f6cc-1f93-4002-9492-345dcef6d0bf.png)
![image](https://user-images.githubusercontent.com/21011265/160835958-3709e0b6-377f-4eab-a899-a5889ef8ddcd.png)
整个流程陷入了死循环，但不管我执行哪个命令，package.json里都没有新增内容，难道要手动在package.json添加吗

**Comment by xiaoyuebao** [comment]
刚试了试在package.json里手动添加了    "hexo-render-pug": "^2.1.4",    "hexo-theme-yun": "1.8.11",然后重新install了一下就好了

**Comment by xiaoyuebao** [comment]
刚试了试在package.json里手动添加了 "hexo-render-pug": "^2.1.4", "hexo-theme-yun": "1.8.11",然后重新install了一下就好了
![image](https://user-images.githubusercontent.com/21011265/160838197-7c3959c7-77e7-484e-ad53-10a20cc48899.png)

**Comment by xiaoyuebao** [comment]
刚才我有重新走了下流程，发现安装hexo-theme-yun就会把node_modules里的hexo-render-pug删掉，安装hexo-render-pug就会把node_modules里的hexo-theme-yun删掉，而且都不会在package.json里增加依赖，只能手动增加依赖，然后npm i才行，这是啥问题

**Comment by YunYouJun** [comment]
……我觉得是你 npm 安装方式有问题，包本身是做不到卸载其他包这件事情的。

**Comment by xiaoyuebao** [comment]
而且我一下执行npm install hexo-theme-yun hexo-render-pug hexo-renderer-stylus，node_modules里pug、stylus、yun依赖倒是都有了，但还是显示缺pug
![image](https://user-images.githubusercontent.com/21011265/160843485-02b86413-8787-46c4-91f2-37bb18f9f26b.png)
![image](https://user-images.githubusercontent.com/21011265/160843384-3dc1af11-2658-489b-8584-ad17ec998f44.png)
只有手动在package.json里添加pug、yun依赖，然后install的才没有问题

**Comment by YunYouJun** [comment]
![96AF4DAB534F7BCF9ED12D9F1DE386F6](https://user-images.githubusercontent.com/25154432/160808306-f17c9152-9cf4-4702-a0f4-16668d07235b.gif)

先用着吧，之后会把主题迁移到 [valaxy](https://github.com/YunYouJun/valaxy)，这些小毛病都解决了。
不需要再安装渲染器了。

**Comment by xiaoyuebao** [comment]
我在Linux子系统上跑了一遍没有这个问题

**Comment by xiaoyuebao** [comment]
我在Linux子系统上跑了一遍没有这个问题，可能是我系统或者npm 或者hexo的问题，

**Comment by xiaoyuebao** [comment]
我又在别人电脑上跑了一遍，也没有问题，原来真是我电脑的问题，吐了

**Comment by YunYouJun** [comment]
（重装保平安）
