### ISSUE TITLE
hexo 的 prism 与 highlight 支持

### ISSUE THREAD

**Issue by yuzijiangorz** [YunYouJun/hexo-theme-yun#28]
我建议，除了Hexo-prism-plugin外，还能用回highlight.js

highlight.js虽然会拖慢机子的运行速度。

但hexo-prism-plugin对C++的不友好，我深有体会

hexo-prism-plugin关于无法渲染C++的问题。issue大大小小提了三个。

可hexo-prism-plugin的作者给出的回答是

这个在我的机子上就有用。

建议你看一下官方文档，我们是支持C++的

啊，要不然你们就用C来渲染C++吧

而且在17，18年后好像也不怎么维护了。issue也不回了。

搞得我真想口吐芬芳

[issue1](https://github.com/ele828/hexo-prism-plugin/issues/56)

[issue2](https://github.com/ele828/hexo-prism-plugin/issues/23)

[issue3](https://github.com/ele828/hexo-prism-plugin/issues/55)

**Comment by YunYouJun** [comment]
关于 hexo-prism-plugin 的确许久不再维护，我之所以仍然在使用它，是因为我打算在 Hexo 5.0 发布后，直接使用 Hexo 内置的 Prism。

> Hexo 5.0 Roadmap 确定会原生支持 Prism https://github.com/hexojs/hexo/issues/4002#issuecomment-568271490

---

关于 C++ 高亮，请尝试使用 `cpp`。

我的 C++ 代码测试正常。

![image](https://user-images.githubusercontent.com/25154432/82061809-c5571e00-96fb-11ea-8034-0e384646e6f6.png)

> https://www.yunyoujun.cn/note/opengl-with-macos/#Progress

**Comment by YunYouJun** [comment]
现已适配 hexo 5.0 原生 prismjs 代码高亮，可移除 hexo-prism-plugin。
使用 CDN 方式加载 prism 样式，同时还可为亮暗模式设置不同模式的代码高亮主题。
