### ISSUE TITLE
页面首次加载有一瞬间没有样式

### ISSUE THREAD

**Issue by QianChenJun** [YunYouJun/hexo-theme-yun#284]
您需要提供的内容：

- 主题版本号（必须）： v1.8.11
- 您遇到的问题（必须）： 我遇到了 页面首次加载有一瞬间没有样式，网页整体特别卡 问题。
  - 截图
 
![Snipaste_2022-04-28_20-15-08](https://user-images.githubusercontent.com/74245184/165749837-e0a750b7-cab9-45c8-9e46-3a0a16437b61.png)

  - 代码仓库（可选）
  - 线上预览地址：www.qianchen.xyz

**Comment by YunYouJun** [comment]
无法复现，关闭 live2D 等不必要的功能试试。

**Comment by QianChenJun** [comment]
关闭live2D后恢复了。
=

**Comment by YunYouJun** [comment]
那别用 live2D 了，可能是样式冲突或太卡了。（
