### ISSUE TITLE
升级 yun 1.7.0 后先上部署多一个大回到顶部的圈圈

### ISSUE THREAD

**Issue by XMuli** [YunYouJun/hexo-theme-yun#285]
今天仅将 Yun 由 1.50 升级到 V1.7.0 (使用 git submodule 管理)；本地 hexo s 预览正常，后部署到远程服务器则每一页都有超大的回到顶部的按钮。暂保留现场 --> [https://ifmet.cn](https://ifmet.cn)

Yun: v1.7.0 (dev branch 401f972e2d789a7917202bf32cd1c5edace18336)

```powershell
// --------------------------- 本机 ---------------------------
Win10 21H2
hexo: 5.4.0
hexo-cli: 4.3.0
os: win32 10.0.19044
node: 14.17.3
v8: 8.4.371.23-node.67
uv: 1.41.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.1
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0

// --------------------------- 远程 ---------------------------
Ubuntu: 20.04
hexo: 5.4.0
hexo-cli: 4.3.0
os: linux 5.13.0-1022-azure Ubuntu 20.04.4 LTS (Focal Fossa)
node: 14.16.1
v8: 8.4.371.19-node.18
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
```

<img width="790" alt="Snipaste_2022-04-29_12-55-32" src="https://user-images.githubusercontent.com/33887845/165887803-d8d7b0c2-412d-47fa-866d-12b20a1a7ea5.png">

若是需要其它详细信息，可 call me，

**Comment by YunYouJun** [comment]
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/25154432/165892663-dbfc3777-075a-4ef4-b99e-e801651a5ea7.png">

看起来显示正常，可能与缓存有关。

**Comment by YunYouJun** [comment]
升吧（

**Comment by XMuli** [comment]
那晚上回去升一下， thanks

<img src="https://user-images.githubusercontent.com/33887845/165895644-8ca3e85b-6e5a-426d-9b66-9aaa80d6e402.jpg" width="30%"/>
