### ISSUE TITLE
[Bug Report] Twikoo 评论系统无法使用

### ISSUE THREAD

**Issue by maxelblack** [YunYouJun/hexo-theme-yun#288]
**Describe the bug**

启用 Twikoo 评论系统之后页面中未显示，控制台报错 Uncaught TypeError

**To Reproduce**

启用 Twikoo 即可

**Screenshots**

我直接上控制台输出吧

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getScript')
    at （索引）:50:1039
```

Chrome Dev Tools 中划错的地方是

```
getScript("https://cdn.jsdelivr.net/npm/twikoo@latest/dist/twikoo.all.min.js", () => {
```

**Desktop (please complete the following information):**

- OS: Windows 10 LTSC 2021 with Node.js 16 LTS
- Browser: Chrome
- Version: 浏览器 101.0.4951.41 | 主题 v1.8.11

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/6d39d3b0c5a0bdbef15a12eadc7b40e86ce75694.
Released in `v1.9.0`.
