### ISSUE TITLE
主题 Hexo g 报错

### ISSUE THREAD

**Issue by huanruomengyun** [YunYouJun/hexo-theme-yun#32]
报错如下
```
ERROR Render HTML failed: categories/index.html                                                 TypeError: /data/data/com.termux/files/home/GA/themes/yun/layout/_mixin/post-collapse.pug:3         1| mixin post_collapse(posts)                                                                   2|   .post-collapse                                                                           > 3|     for post in posts.data                                                                   4|       if !post.hide || post.hide === 'index'                                                 5|         - var year                                                                           6|         - var post_year = date(post.date, 'YYYY')
```

**Comment by YunYouJun** [comment]
能否提供可复现的代码仓库？

**Comment by huanruomengyun** [comment]
> 能否提供可复现的代码仓库？

仓库地址：https://github.com/huanruomengyun/tmp

**Comment by YunYouJun** [comment]
有三处问题：

https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46

此处的 `!=yun_config()` 被注释掉了。

---

https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L179

此处没有用到 categories 的颜色，可以直接删掉，留空则会强制覆盖默认的配置，造成分类为空。

---

https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L69

此处的 monospace 字体缩进有问题。如果不需要自定义字体，可以直接删掉此部分配置，将会自动使用默认配置。

**Comment by huanruomengyun** [comment]
> 有三处问题：
> 
> https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46
> 
> 此处的 `!=yun_config()` 被注释掉了。
> 
这里是我手动注释的，因为如果不注释这里，这里也会报错……

**Comment by YunYouJun** [comment]
> > 有三处问题：
> > https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46
> > 此处的 `!=yun_config()` 被注释掉了。
> 
> 这里是我手动注释的，因为如果不注释这里，这里也会报错……

此处原因为未配置 algolia appID，却开启了 `algolia_search`。

**Comment by huanruomengyun** [comment]
> > > 有三处问题：
> > > https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46
> > > 此处的 `!=yun_config()` 被注释掉了。
> > 
> > 
> > 这里是我手动注释的，因为如果不注释这里，这里也会报错……
> 
> 此处原因为未配置 algolia appID，却开启了 `algolia_search`。

问题已解决，感谢~

**Comment by huanruomengyun** [comment]
> 有三处问题：
> 
> https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46
> 
> 此处的 `!=yun_config()` 被注释掉了。
> 
> https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L179
> 
> 此处没有用到 categories 的颜色，可以直接删掉，留空则会强制覆盖默认的配置，造成分类为空。
> 
> https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L69
> 
> 此处的 monospace 字体缩进有问题。如果不需要自定义字体，可以直接删掉此部分配置，将会自动使用默认配置。

我好像又碰到问题了……报错如下
```
TypeError: /root/GA/themes/yun/layout/_mixin/post-collapse.pug:3
1| mixin post_collapse(posts)                                      
2|   .post-collapse
 > 3|     for post in posts.data                                                    4|       if !post.hide || post.hide === 'index'
    5|         - var year                                                      
6|         - var post_year = date(post.date, 'YYYY')
                                                                              
Cannot read property 'data' of undefined
```

我在没有安装 hexo-render-pug 的时候可以正常 hexo g，但是本地调试时会提示要求安装 hexo-render-pug。安装 hexo-render-pug 后 hexo g 报错如上。

**Comment by huanruomengyun** [comment]
> > 有三处问题：
> > https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/themes/yun/layout/_partial/head.pug#L46
> > 此处的 `!=yun_config()` 被注释掉了。
> > https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L179
> > 此处没有用到 categories 的颜色，可以直接删掉，留空则会强制覆盖默认的配置，造成分类为空。
> > https://github.com/huanruomengyun/tmp/blob/6a0e804cd92723c914a397aff3e9299fb83617c5/source/_data/yun.yml#L69
> > 此处的 monospace 字体缩进有问题。如果不需要自定义字体，可以直接删掉此部分配置，将会自动使用默认配置。
> 
> 我好像又碰到问题了……报错如下
> 
> ```
> TypeError: /root/GA/themes/yun/layout/_mixin/post-collapse.pug:3
> 1| mixin post_collapse(posts)                                      
> 2|   .post-collapse
>  > 3|     for post in posts.data                                                    4|       if !post.hide || post.hide === 'index'
>     5|         - var year                                                      
> 6|         - var post_year = date(post.date, 'YYYY')
>                                                                               
> Cannot read property 'data' of undefined
> ```
> 
> 我在没有安装 hexo-render-pug 的时候可以正常 hexo g，但是本地调试时会提示要求安装 hexo-render-pug。安装 hexo-render-pug 后 hexo g 报错如上。

我之前好像也碰到了这个问题，当时直接注释了相关代码……

**Comment by YunYouJun** [comment]
你此前的项目，我解决那三处，就已经可以正常运行了。
此后有卸载渲染器？

**Comment by huanruomengyun** [comment]
> 你此前的项目，我解决那三处，就已经可以正常运行了。
> 此后有卸载渲染器？

我之前是在手机的 Termux 配置 Hexo 环境并部署到 GitHub Page，但是我本地的环境貌似炸了，hexo clean && hexo g 直接返回 `Error: write EPIPE`
所以我干脆在我服务器上 clone 仓库进行配置，然后报错如上。

**Comment by huanruomengyun** [comment]
> 仓库代码看看？

仓库地址：https://github.com/huanruomengyun/tmp-
（1M 小水管上传有点慢，见谅…）

**Comment by YunYouJun** [comment]
> > 仓库代码看看？
> 
> 仓库地址：https://github.com/huanruomengyun/tmp-
> （1M 小水管上传有点慢，见谅…）

不传 `node_modules` 就行了……

**Comment by YunYouJun** [comment]
……你这 node_modules 没装好吧，我删掉重装就跑起来了。

以及你这依赖未免太多了，很多没用到的可以卸载掉的。

**Comment by huanruomengyun** [comment]
> ……你这 node_modules 没装好吧，我删掉重装就跑起来了。
> 
> 以及你这依赖未免太多了，很多没用到的可以卸载掉的。

我删掉重装还是一样的报错……
有些依赖是用其他主题或当时用其他功能安装了，一直没删…

**Comment by YunYouJun** [comment]
标签页 `tags/index.md` 与归档页 `categories/index.md` 使用的是 `type` 而不是 `layout`。

如：

```md
---
date: 2017-10-09 19:11:58
type: tags
comments: false
---
```

**Comment by huanruomengyun** [comment]
> ……你这 node_modules 没装好吧，我删掉重装就跑起来了。
> 
> 以及你这依赖未免太多了，很多没用到的可以卸载掉的。

我新建了一个文件夹并初始化，仅安装主题所必需依赖后，还是那个报错。

**Comment by YunYouJun** [comment]
见上方的回复。是这个问题，我测试可行。
看你你之前使用的主题是通过 `layout` 设置的吧。
此处著名的 next 与 melody 等主题，均使用 `type` 字段设置，所以我也参考使用了 `type`。

**Comment by huanruomengyun** [comment]
> 见上方的回复。是这个问题，我测试可行。
> 看你你之前使用的主题是通过 `layout` 设置的吧。
> 此处著名的 next 与 melody 等主题，均使用 `type` 字段设置，所以我也参考使用了 `type`。

已本地调试确认可用，谢谢大佬啦
