### ISSUE TITLE
希望能支持Latex插件$行内公式

### ISSUE THREAD

**Issue by Pakchoi1** [YunYouJun/hexo-theme-yun#37]
因为使用typora进行编辑，所以使用的$行内公式在博客无法渲染，\\(\\)在typora又无法渲染
所以希望可以支持

**Comment by YunYouJun** [comment]
这个问题此前有讨论考虑过。

本主题使用的是 [KaTeX](https://github.com/KaTeX/KaTeX) 解析器，而其默认的解析规则是 `$$` `\(` `\[` 。$ 行内公式无法解析，是因为 KaTex 的规则会和 `$$` 混淆，因为上游的解析问题，主题无法对此进行修改。

其次，也许更为强大的 [MathJax](https://github.com/mathjax/MathJax) 能够解决你的问题，但 MathJax 相比 KaTeX 要大上许多，本主题希望能在实现基础功能前提下成为一个较为轻量的主题，所以不打算适配加入 MathJax。

> 也许 hexo 的一些第三方的数学公式插件能够解决这个问题，您可以尝试一下。

最后，如果文章对公式的要求程度很高，我个人建议可以考虑直接使用 [Overleaf](https://www.overleaf.com/)、[语雀](https://www.yuque.com/login?platform=wechat&inviteToken=f44225123bcab02038f11cc0a7ab720c6d41f5952d55ea25f6596890ceff74fb)、[Notion](https://www.notion.so/) 等工具。

然后想将其分享到自己的博客，则可以使用本主题的特色功能 - [内容卡片](https://yun.yunyoujun.cn/guide/config.html#%E5%86%85%E5%AE%B9%E5%8D%A1%E7%89%87)。（将会显示对应链接的 LOGO 和商标色）Notion 添加计划中...

---

以上是本主题不会对该功能进行支持的原因，如果您有更好的想法和建议欢迎提出。
如果您可以接受该做法，请关闭当前 ISSUE。

**Comment by YunYouJun** [comment]
@Pakchoi1 好消息，KaTeX 支持了 `$$` `$` 的渲染顺序，所以主题已进行了适配，行内公式 `$E=mc^2$` 的方式已经可以实现了。

当前尚未 release，但您可以拉取 dev 分支试用。
