### ISSUE TITLE
[Bug Report]友链图片可能出现onerror="this.src=CONFIG.anonymous_image"问题

### ISSUE THREAD

**Issue by MEMZSONBILI** [YunYouJun/hexo-theme-yun#38]
**Bug描述：**
本人与池塘互换友链后友链图片无法加载，用F12查看友链图片对应HTML出现“onerror="this.src=CONFIG.anonymous_image“”
问题，已排除图床（本人使用js，池塘使用路过s1），浏览器（本人Firefox75.0，池塘New Edge 83.0.478.54）问题。
**复现步骤（目前仍保留问题）：**
https://chi-tang-github.github.io/links/ 中Eden瞎写小屋的图片
和
https://edenjohnson.me/links/ 中 Chi_Tang‘s Blog的图片

**截屏**
![](https://cdn.jsdelivr.net/gh/MEMZSONBILI/PicGoBed@master/images/20200627194858.png)
![](https://cdn.jsdelivr.net/gh/MEMZSONBILI/PicGoBed@master/images/20200627194940.png)

**双方状况**

- OS: macOS10.15.5 19F101/Windows 10 20H2 19631.1
- Browser: Firefox /Edge Chromium
- Version: 75.0.1/83.0.478.54

**附加描述**
确定与图片懒加载无关。

**Comment by YunYouJun** [comment]
请提供一下友链页面头部的书写配置或 GitHub 博客 Hexo 源文件仓库。

**Comment by MEMZSONBILI** [comment]
> 请提供一下友链页面头部的书写配置或 GitHub 博客 Hexo 源文件仓库。

书写如下，已由VSCode排版。
```---
layout: links
title: links
date: 2020-06-26 10:48:14
links:
  - url: https://lijiakaijun.me
    avatar: https://s1.ax1x.com/2020/04/07/GcmGMd.jpg
    name: +酱（认真）
    blog: lijiakaijun
    desc: 随便写写...
  - url: https://xfox.fun
    avatar: https://secure.gravatar.com/avatar/71951168fe46b1781ecc3db5041f5b74?s=32&r=X&d=
    name: 未知狐
    blog: XFOX | 未知狐的小窝
    desc: 别离一瞬最难忘，君不见，思断肠。
  - url: https://chi-tang-github.github.io
    avator: https://s1.ax1x.com/2020/06/27/N6TFbQ.jpg
    name: Chi_Tang
    blog: Chi_Tang's Blog
    desc: 只是一个普通的初中生罢了。
    color: "#0071bc"
    email: "bilibilichitang@hotmail.com"
placeholder: 
---

**Comment by YunYouJun** [comment]
拼写错误， `avator` 应当为 `avatar`。

```
avator: https://s1.ax1x.com/2020/06/27/N6TFbQ.jpg
```

**Comment by YunYouJun** [comment]
如果修改拼写后，问题已得到解决，可以关闭该 ISSUE。

**Comment by YunYouJun** [comment]
没有后续反馈，默认已得到解决，将关闭该 ISSUE。
