### ISSUE TITLE
Safari 主页显示不全(Chrome正常

### ISSUE THREAD

**Issue by ANh0r** [YunYouJun/hexo-theme-yun#4]
排查之后发现是Safari报错
在banner.js 
CharBox.animate{
}
打开WebAnimations之后可以。
在Yun官网的网页js没有用到这个函数..

version是在md文档下载的版本。

**Comment by YunYouJun** [comment]
谢谢你的反馈，这个问题已在昨日的 dev 分支修复，你可以尝试使用最新的 dev 分支版本。可以看这里。
https://github.com/YunYouJun/hexo-theme-yun/issues/3#issuecomment-597111530

**Comment by YunYouJun** [comment]
如果没有其他问题，该 Issue 就先关闭了。你仍然可以继续在下方回复。
