### ISSUE TITLE
同一个图文网页， 在 27 寸上显示为图片异常大，不便于看文章

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#40]
使用 yun 主题后，对于大屏幕的网页中图片显示体验不佳， 若是可以改进， 非常感激~~~

7.2 改日 yun 修复后，现在 设置如下 `<img src="https://cdn.jsdelivr.net/**.png" width="50%" />` 后，虽然确实是屏幕的 50% 宽度， 但是图片依旧很大；  且尝试将照片大小写死， 如 `<img src="*.jpg" width="400" height="400" />`, 根本没有其效果， 依旧被强制拉大；

**当前效果：**
在小屏幕上看上还好的文章， 在切换到大屏幕上，图片会被加载的过于巨大，但是文字还是那么的小，及其影响阅读体验；

**预期效果：**
在不同的屏幕上，13.3， 27.， 32 寸 (尤其是大屏幕上)的显示屏幕上看文章的时候，文字是可以自动换行（根据宽度的）； 但是照片可以保持同样大小（无论多大屏幕， 其最后肉眼看到的屏幕网页， 图片大小都是固定的，协调）

**建议：**
1. 将所有加载图片的地方的宽度都写死， 那样使用 `<img src="*.png" width="50%" />` 这种的话，就可以在写 markdown 插入图片时候， 很好的即时预览效果。
2. 或 其他方案？ 我未可知

**补充：**
版本：由 Hexo 驱动 v4.2.1|主题 - Yun v0.9.2
实例： 预览网页 [使用 CDN 加速你的 GitHub Pages 网站](https://www.yunyoujun.cn/note/use-cdn-speed-up-site/)

![image](https://user-images.githubusercontent.com/33887845/86469445-f94dd780-bd6b-11ea-8520-031e586d6147.png)
![image](https://user-images.githubusercontent.com/33887845/86469543-35813800-bd6c-11ea-8084-03f9e46fdf4d.png)

若是不方便调试，附上附件一份：

[github加载图片丢失解决方案的副本.md.zip](https://github.com/YunYouJun/hexo-theme-yun/files/4869690/github.md.zip)

最后希望效果，能够同一个网页，在小屏幕看完觉着合适后， 大屏幕看着图文比例大小也很协调即可。
**强烈建议，若是有优化之后，能够是物理的 13.3 ，27， 32 寸这种物理屏幕上体验一下效果；确保最后观看效果**

源于是对 yun 主题的喜爱， 提出一个建议； 希望采纳；

**Comment by xmuli** [comment]
已赞助， 略表心意，对主题喜爱之情

**Comment by YunYouJun** [comment]
想要强制写死大小，可以使用 `<img style="width: xxxpx;"/>` 的形式覆盖。

事实上，这张截图的长宽为 `1592 × 1356`。在小屏幕时，属于缩放状态。大屏幕时，相当于显示了原本真正的高宽。
没有办法知晓用户究竟期待这张图能够全部显示（因为此前有朋友提出如何显示长图不被缩放，所以我取消了具体高度的限制），还是希望正常缩放。

文字应该本身就是可以自动换行的。

图片若写死 50% 宽度，可能反过来对小屏幕会不友好。
解决方案我目前考虑了两种，一种还是限制最高宽度，让宽度和告诉成比例缩放，第二种则是使用媒体查询针对大屏幕，专门写一下图片的宽高样式。目前尝试采用了第一种做法。

以及最后我的确也想在物理大屏幕上实验下，但我确实没有这么大的屏幕…… 只能使用浏览器缩放模拟，无法真正确认实际效果。
所以还是得请你确认一下。

> https://www.yunyoujun.cn/note/use-cdn-speed-up-site/

---

感谢支持，已添加进[赞助列表](https://sponsors.yunyoujun.cn/list)中。

**Comment by xmuli** [comment]
> 想要强制写死大小，可以使用 `<img style="width: xxxpx;"/>` 的形式覆盖。

这个是指代表的？ 再 yun 的 css 里面，设置， 还是在 markdown 写这个？； 看到你里面图片这个在 27 确实是有缩小了（这张图看起来协调了，小屏幕也可以接受）， 但是其他的图片好像没有比变小？（只是单独对那一个图片设置大小了？看到 markdown 好像没有修改？？）

> 没有办法知晓用户究竟期待这张图能够全部显示（因为此前有朋友提出如何显示长图不被缩放，所以我取消了具体高度的限制），还是希望正常缩放。
这个我建议还是显示为暂时统一显示为缩略图，，，事实上， 整体来看， 发布一百篇博客， 也很少有用到长截图效果；从工作量上和体验上来看， 可以先适当的做减法（图文太长完全应该点击一下， 此案时看看长图）

效果如图：
27-4K：效果==>
![27_4K](https://user-images.githubusercontent.com/33887845/86502913-00f89500-bddb-11ea-9a72-bc68924603b2.png)


13.3-2K：效果==>
![13 3_2K](https://user-images.githubusercontent.com/33887845/86502926-1ec5fa00-bddb-11ea-9ff5-a0a7d855bc61.png)


我在文章中， markdown 是使用 <image> 网页标签方式插入图片的； 以前也是  `![13 3_2K](https://....)` 格式来写， 后来发现，文章同步到 csdn 中，会有的图片会被转载不出来， 但是使用 标签 <image> 则可以显示， 不会被吞掉图片。

**Comment by YunYouJun** [comment]
可以自定义 CSS 设置，也可以在文章中单独设置 img 标签大小。

想要左对齐还是右对齐，同样可以在 markdown 中自定义 img 样式实现。
（markdown 本身语法没有左右对齐，解析只会获得普通的 img 标签，所以需要直接写 img 标签的样式自定义。）

因为主题样式与 markdown 样式已分离，本质为修改的 [star-markdown-css](https://github.com/YunYouJun/star-markdown-css) 的样式。并非对单独图片进行了设置，我设置了最大高度。

我现在尝试使用媒体查询，对 1600px 宽度以上的屏幕，设置了图片最大宽度不超过 800px，小于此宽度的屏幕图片，最大宽度则为文章页面宽度的 92%；我 Chrome 模拟效果还行，不是物理设备效果如何？

**Comment by xmuli** [comment]
现在效果预览， 是可以处于接受（没有之前那么影响观看了， 阅读效果舒适了很多）的状态；赞

 > 因为主题样式与 markdown 样式已分离，本质为修改的 star-markdown-css 的样式。并非对单独图片进行了设置，我设置了最大高度。

这个我改如何升级呢？ 因为它是在另外一个仓库中，有点难倒了我了；

> 对 1600px 宽度以上的屏幕，设置了图片最大宽度不超过 800px，小于此宽度的屏幕图片，最大宽度则为文章页面宽度的 92%；

这个想法很棒， 效果也是可以的，已经预览过了，效果都可以； 可我若是想要自己尝试设置一些更合适参数？
`不超过 800px` 和 `宽度的 92%`  ，  该如何修改哪一个文件？（我这里只有一个 yun 主题文件夹）

抱歉： 涉及前端知识比较匮乏😶😶

**Comment by YunYouJun** [comment]
看到您此前编辑的内容，现在应该已经自行解决了问题。

以防后续类似问题，我在此说明一下吧。

---

虽然分割了 star-markdown-css，但不需要操心 markdown 样式的更新，主题将会默认引入锁定版本的 markdown CDN。
同时这么做还有一个好处就是，你甚至可以覆盖主题引入的 markdown 样式，更换为任意你喜欢的样式。只要是以 `.markdown-body` 命名空间即可。（当然肯定我这自身适配的好些，王婆卖瓜。）

想要自定义样式的话，只需自己建立 `source/css/xxx.css`，并在 [head](https://yun.yunyoujun.cn/guide/config.html#head-%E5%A4%B4%E9%83%A8%E8%B5%84%E6%BA%90) 中引入即可。

想要引用主题已有的变量，也可以使用 `stylus` 编写。[自定义样式](https://yun.yunyoujun.cn/guide/config.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)

---

因为主题是一种较为统一的风格，难免各位都有一些自定义的特殊需求，所以提供了多种自定义方式，大可在不修改主题文件的情况下进自定义。不直接修改主题文件，也能更方便日后的更新。

**Comment by YunYouJun** [comment]
如果没有后续问题，则请关闭当前 ISSUE。

**Comment by xmuli** [comment]
为了尽可能少打扰到你， 所以翻看了与其相关的commit， 继续结合和尝试验证，所以后面成功出来了。 thanks
后面的完整解释验证了我的猜测，有帮助到我。😄😄
