### ISSUE TITLE
[Feature Request]能否在配置文件中增添自定义字体大小这一功能？

### ISSUE THREAD

**Issue by huanruomengyun** [YunYouJun/hexo-theme-yun#43]
在目前 Yun 的默认字体配置中，二级标题大小默认会大于文章标题。这在桌面端视觉上有着不错的体验，但是在移动端的表现大多时候不尽人意（尤其是当二级标题字数过多的情况下）

移动端显示效果大致如下：
![Screenshot_20200709-085617~2](https://user-images.githubusercontent.com/59136309/86984785-1fd39e80-c1c2-11ea-933a-69e6f6cfcc64.png)

如果桌面端和移动端的字体大小都可以分别单独定义，无疑是最优处理方案.

**Comment by YunYouJun** [comment]
![Screenshot_2020-07-09-13-28-49-344_com android ch](https://user-images.githubusercontent.com/25154432/87001174-638dce80-c1e9-11ea-8fa3-8554a7c59424.jpg)

其实我自己还算满意，感觉主要标题也不应过长。较长的本身是否作为三级、四级标题更合适？

如：

```md
## 步骤

### 对 xxx 进行全面更新
```

两边的标题大小也单独定义的话也可以，但感觉未必必要。

我先尝试略微缩小标题看看效果。

**Comment by YunYouJun** [comment]
缩小标题后桌面端的标题就显得平庸了，……你是对的，还是单独适配效果更好点。
现在单独对移动端略微缩小了字体（我觉得标题字数也的确可以缩减一点），可拉取最新开发版查看效果。

**Comment by huanruomengyun** [comment]
> 缩小标题后桌面端的标题就显得平庸了，……你是对的，还是单独适配效果更好点。
> 现在单独对移动端略微缩小了字体（我觉得标题字数也的确可以缩减一点），可拉取最新开发版查看效果。

缩小后体验不错，谢谢啦
