### ISSUE TITLE
暗色主题下，显示文章预览现代码片问全白异常

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#44]
chrome 中发现的，选中才会清楚显示预览代码， 代码片在文章里面则是正常， 可验证的 [https://xmuli.tech](https://xmuli.tech)

![image](https://user-images.githubusercontent.com/33887845/87148890-d11d2600-c2e1-11ea-9199-62b7fefcc657.png)

**Comment by YunYouJun** [comment]
Thanks. Fixed: https://github.com/YunYouJun/hexo-theme-yun/commit/47a26f7ca8d506eafe18d145d74243a080917674
