### ISSUE TITLE
[Bug Report] 低分辨率屏幕下 300 字重的显示效果

### ISSUE THREAD

**Issue by YunYouJun** [YunYouJun/hexo-theme-yun#45]
**Describe the bug**
低分辨率屏幕下，300 字重可能显示效果较差问题。

> @leostudiooo
> Hmmm因为300字重对低分屏（1080以内）的适配不太好，过于细了，甚至发虚，我觉得如果默认400或者350就好一些。
> https://github.com/YunYouJun/hexo-theme-yun/issues/3#issuecomment-657214155

**Comment by leostudiooo** [comment]
## font-weight 900(Serif)/300(Sans-serif) 显示效果
https://yunyoujun.cn/note/make-el-bot
![image](https://user-images.githubusercontent.com/35419343/87309442-31fd6600-c54f-11ea-9565-42149857bcf9.png)

## font-weight 900(Serif)/500(Sans-serif) 显示效果
https://leostudiooo.github.io/2020/07/04/how-to-make-an-open-source-dial/
![image](https://user-images.githubusercontent.com/35419343/87309854-be0f8d80-c54f-11ea-9edd-348a868cd645.png)

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/87324071-2c5d4b80-c562-11ea-89de-2a56787b6b78.png)
![image](https://user-images.githubusercontent.com/25154432/87324125-41d27580-c562-11ea-9862-8e447421d4b1.png)

emm，mac 平台下效果还不错，可能是分辨率比较高的原因？

微软雅黑的 300 字重看起来也还不错：

![image](https://user-images.githubusercontent.com/25154432/87324684-07b5a380-c563-11ea-8fe6-af0a77de64d4.png)

**Comment by YunYouJun** [comment]
几经对比，我感觉还是更喜欢轻一点的字重。

所以如果更喜欢 400 字重的话，还是直接通过配置文件自定义吧。

```yaml
font:
  sans_serif:
    family: "'PingFang SC', 'Microsoft YaHei', Roboto, Arial, sans-serif"
    weight: 400
```

**Comment by leostudiooo** [comment]
> ![image](https://user-images.githubusercontent.com/25154432/87324071-2c5d4b80-c562-11ea-89de-2a56787b6b78.png)
> ![image](https://user-images.githubusercontent.com/25154432/87324125-41d27580-c562-11ea-9862-8e447421d4b1.png)
> 
> emm，mac 平台下效果还不错，可能是分辨率比较高的原因？
> 
> 微软雅黑的 300 字重看起来也还不错：
> 
> ![image](https://user-images.githubusercontent.com/25154432/87324684-07b5a380-c563-11ea-8fe6-af0a77de64d4.png)

正因为Mac分辨率较高（MacBook系列为2k，iMac系列为4k或5k）并且字体渲染也很强所以边缘不发虚。你把我的截图放大到全屏看起来就会有虚边。

BTW微软雅黑对低分屏有字形结构和显示效果优化，所以就算字重300也不会出现可读性降低的情况。

**Comment by leostudiooo** [comment]
截屏展示效果可能不是很明显，给你看看实际显示效果（原图较大 请耐心等候）：

![IMG_20200714_113207](https://user-images.githubusercontent.com/35419343/87380793-d15d4000-c5c5-11ea-9cd8-6edc7ef29afb.jpg)
![IMG_20200714_113153](https://user-images.githubusercontent.com/35419343/87380813-db7f3e80-c5c5-11ea-98b5-94d00f705bf3.jpg)

**Comment by YunYouJun** [comment]
请问当前是何系统？系统默认首选字体是什么？

**Comment by leostudiooo** [comment]
OS Version:
- Windows 10 Pro x64, Insider Preview 2003

Default font-family: 
- Sans-serif: Microsoft Yahei（微软雅黑）
- Serif: Simsun（宋体）
- Monospace: Monaco

PingFang SC和Source Han Sans Pro也是可用的。

**Comment by YunYouJun** [comment]
该 ISSUE 暂时先保持开启，我尝试下是否有更好的解决方案。

**Comment by leostudiooo** [comment]
好的

发自我的华为手机


-------- 原始邮件 --------
发件人： 云游君 <notifications@github.com>
日期： 2020年7月14日周二 20:20
收件人： YunYouJun/hexo-theme-yun <hexo-theme-yun@noreply.github.com>
抄送： Leo Lingfeng Li <lilingfeng0408@outlook.com>, Mention <mention@noreply.github.com>
主 题： Re: [YunYouJun/hexo-theme-yun] [Bug Report] 低分辨率屏幕下 300 字重的显示效果 (#45)

该 ISSUE 暂时先保持开启，我尝试下是否有更好的解决方案。

―

**Comment by YunYouJun** [comment]
> BTW微软雅黑对低分屏有字形结构和显示效果优化，所以就算字重300也不会出现可读性降低的情况。

此时我也考虑可以将 `Microsoft Yahei` 放置于 `PingFang SC` 之前，以解决这个问题。但这意味着 mac 用户安装了 Office 等办公软件时，将割舍掉 `PingFang SC` 这一原生优化而美观的字体，通样得不偿失。

强制使用自定义字体，譬如 `Noto Sans SC` 以实现多平台的显示风格统一，也是一种方案，但中文字体往往过大，不是很划算。

几番纠结后，我将字体默认字重设置为了 400，并减淡了字体颜色和次级的字体颜色。

@leostudiooo 可否看看效果如何？[云游君的小站](https://www.yunyoujun.cn)

当然，如果有更好的建议，欢迎提出。

**Comment by leostudiooo** [comment]
效果非常棒！
非常感谢采纳我的建议！
400是一个介于更粗和更细之间的极佳解决方案，在23寸1080p屏幕上的显示效果刚好合适。

**Comment by YunYouJun** [comment]
感谢您的建议。

当前内容已在开发版（dev 分支）可用。https://github.com/YunYouJun/hexo-theme-yun/commit/76373cad576a48f339fd6e02e5194d15ab0d48d1
将在周末 release v0.9.4。
