### ISSUE TITLE
暗模式下， 搜索栏的文字颜色过浅，看不清

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#46]
yun 主题在黑暗模式下，搜索栏里面的字体颜色过浅， 建议加深

![image](https://user-images.githubusercontent.com/33887845/87520446-90445900-c6b5-11ea-9598-ec86cc521b0b.png)

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/87528031-8de6fc80-c6bf-11ea-8142-efba0f7ffaca.png)

……之前只加了 algolia，local-search 没用没注意。

Fixed: https://github.com/YunYouJun/hexo-theme-yun/commit/141fbfc788df891e8c5e30fc08867e1636afde53
