### ISSUE TITLE
 yun 是不支持 右上角角标？

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#47]
是还不支持 右上角、右下角的角标吗？还是已经支持？需要自己安装插件
![image](https://user-images.githubusercontent.com/33887845/87873748-7fb61a80-c9f6-11ea-8f77-fc938e25db5c.png)

期望效果：和其他一样
![image](https://user-images.githubusercontent.com/33887845/87873770-b1c77c80-c9f6-11ea-93ca-25f90defca49.png)

[原文链接](https://xmuli.tech/posts/29ffae87/)

PS： 没有催促维修之意，单单询问一下，不过建议加上此功能更好？

**Comment by YunYouJun** [comment]
是指这个吗？2<sup>10</sup>

可以直接使用 html 标签。因为 `^ ^` 不是 markdown 的标准语法。

```md
2<sup>10</sup>
```

**Comment by xmuli** [comment]
多谢
