### ISSUE TITLE
[Feature Request] 添加配置项决定侧边栏导航是否完全展开

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#48]
文章里面的左侧导航，能加一个开关？启动后，默认全部文章的导航都展开（包含二级、 三级标题）

**Comment by YunYouJun** [comment]
Good idea. 之后实现。
此外应该还可以为每篇文章 Front matter 也提供一个配置选项，这样可以自由决定某篇特殊的文章目录是否展开。

**Comment by xmuli** [comment]
> 这样可以自由决定某篇特殊的文章目录是否展开。

要么都折叠，要么都展开，统一即可；虽说单独制定每一篇文章这样的可自定义更高，但个人看法是不好的，破坏了整体的协调统一，访客容易困惑，同一个网站中，文章反而到底是折叠还是没有被折叠？？？（适当的限制或许更好，而非完全的开发视角）

当然，只是建议，采纳与否，需你自行斟酌，言毕；

**Comment by YunYouJun** [comment]
已为目录添加 `collapse` 选项，决定是否折叠目录。（默认折叠）

关闭折叠：

```yaml
toc:
  collapse: false
```

最终没有添加 collapse 的 front-matter，因为此部分使用 css 实现，统一设置似乎更简洁。

**Comment by xmuli** [comment]
更新后主题后， 在 /yun/_config.yml 添加此行？

**Comment by YunYouJun** [comment]
@xmuli 主题更新后，在 `yun.yml` 里加就可以了，主题配置文件已经自带了。
不过现在在开发版分支，明天再一起 release v0.9.5。
