### ISSUE TITLE
[Bug Report]相册外链图片无法正常加载

### ISSUE THREAD

**Issue by sxdl** [YunYouJun/hexo-theme-yun#49]
相册外链图片无法正常加载

**Describe the bug**
在使用`yun`主题中的相册功能，会发现有时相册图片外链链接无法加载的问题

**Screenshots**
[无法加载的图片](https://sxdl.github.io/2020/07/28/%E7%9B%B8%E5%86%8C%E5%A4%96%E9%93%BE%E5%9B%BE%E7%89%87%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E5%8A%A0%E8%BD%BD%E7%9A%84%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/1.png)

**Desktop (please complete the following information):**

- OS: win10
- Browser: chrome
- Version [84.0.4147.89（正式版本） （64 位）]

**Additional context**
具体原因不知道，但是在`<head>`中加入`<meta name="referrer" content="no-referrer"/>`标签后问题解决
参考：https://www.cnblogs.com/guozhaoxin/p/11934483.html

**Comment by YunYouJun** [comment]
这个应该是图片本身使用 referrer 实现防盗链的举措，而设置 no-referrer 则绕开了这一限制。
博客本身是互相链接的，保留 referrer 可以获取统计来源信息。所以更好的方式应当是设置你的图床限制。

也将考虑仅在相册页启用添加该标签。

**Comment by YunYouJun** [comment]
为 `type: albums` 与 `layout: gallery` 类型页面添加 `<meta name="referrer" content="no-referrer" />` 以解决部分图片防盗链问题。
