### ISSUE TITLE
[Feature Request] 右侧联系方式链接的按钮能否设计为随模式改变？

### ISSUE THREAD

**Issue by EdenJohnson2006** [YunYouJun/hexo-theme-yun#50]
使用主题约1个月了，设计还是不错的，只不过有一个问题比较困扰

右侧联系方式中有GitHub的链接，在白天模式下显示还是可以的

但是一到夜晚模式就会出现GitHub按钮看不见的问题

如果屏幕色域比较全，这个问题会比较轻微

但是在平价笔记本上（一般这些电脑上的内置显示屏色域不全比如我这台小米笔记本）则可能出现较为严重的问题
 
我希望的是能够随着模式改变右侧联系方式按钮

比如白天模式下一套

夜晚模式下另一套

这样的话问题将会大幅度改善

希望能够采纳。

附上：黑夜模式下GitHub按钮的显示情况

![](https://cdn.jsdelivr.net/gh/EdenJohnson2006/PicGoBed/images20200731205533.png)

**Comment by YunYouJun** [comment]
你可以和我一样将 GitHub 的商标色设为 `#6e5494`，或将 GitHub 设置为纯黑色，它将自动适配为白色。

![image](https://user-images.githubusercontent.com/25154432/89039369-863c7e80-d374-11ea-9bd7-4c6fede02cd2.png)

**Comment by YunYouJun** [comment]
如果你仍有疑惑可以重新开启该 ISSUE。
