### ISSUE TITLE
原来Iconfont引入的图标现在不能用了

### ISSUE THREAD

**Issue by GloomyM** [YunYouJun/hexo-theme-yun#51]
原来Iconfont在更新到0.9.4后不能用了，原来的版本是0.7.0
`
head:
  css:
    mouse: https://personalblog-1301685299.cos.ap-nanjing.myqcloud.com/MyBlog-Css/Mouse/mouse.css
  js:
    async:
      iconfont: //at.alicdn.com/t/font_1738646_0quryxfab6q.js
`这个是我head里引入的

**Comment by YunYouJun** [comment]
请提供仓库与预览地址。

**Comment by GloomyM** [comment]
> 
> 
> 请提供仓库与预览地址。

https://github.com/GloomyM/GloomyM.github.io/tree/hexo

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/89287804-2c46fc00-d687-11ea-8e19-3d1829d2af3b.png)
不是全都正常么？

**Comment by GloomyM** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/25154432/89287804-2c46fc00-d687-11ea-8e19-3d1829d2af3b.png)
> 不是全都正常么？

中间三个图标我是引入的iconfont，但是没显示出来= =

**Comment by YunYouJun** [comment]
……你这个问题没提到关键点上，比对 [导航配置](https://yun.yunyoujun.cn/guide/config.html#%E5%AF%BC%E8%88%AA) 更新一下你的配置……

**Comment by GloomyM** [comment]
> 
> 
> ……你这个问题没提到关键点上，比对 [导航配置](https://yun.yunyoujun.cn/guide/config.html#%E5%AF%BC%E8%88%AA) 更新一下你的配置……
解决了，感谢云游~~~~~~~
