### ISSUE TITLE
[Feature Request]建议提高主题兼容性

### ISSUE THREAD

**Issue by leostudiooo** [YunYouJun/hexo-theme-yun#52]
如题。

- 主题版本：0.9.1

------
在QQ（built-in）和华为浏览器中无法正常打开页面。更换Chrome或Safari后正常。

QQ:
![1596616088094](https://user-images.githubusercontent.com/35419343/89390018-bef3a380-d738-11ea-9b12-f46e56cafcd8.jpeg)

华为:
![Screenshot_20200805_162918_com android browser](https://user-images.githubusercontent.com/35419343/89390148-e8acca80-d738-11ea-9ee5-1d78ef37dd0f.jpg)

chrome:
![Screenshot_20200805_153907_com android chrome](https://user-images.githubusercontent.com/35419343/89390186-f6625000-d738-11ea-9ae2-bc74ea5c89b2.jpg)

**Comment by YunYouJun** [comment]
我的 QQ 内置浏览器、QQ 浏览器与小米浏览器测试正常，我觉得更可能与安卓系统 Webview 版本，网络环境及浏览器自身的屏蔽策略有关。

主题开发时，的确多选择最新语法特性，中途为了兼容问题，也有重构过，均使用 [caniuse](https://caniuse.com/) 里大部分浏览器支持的特性。做过多兼容（比如 IE 的级别），会有冗余代码，看起来不优雅，所以不打算花时间在这上面。

以及华为似乎好像有挺多这种情况？

https://cn.club.vmall.com/huawei/game/web.php?mod=viewthread&tid=22405779
https://cn.ui.vmall.com/thread-22916552-1-1.html

**Comment by leostudiooo** [comment]
Guess what?我刚刚QQ和华为浏览器都能访问了（捂脸）

我猜这个issue可以关闭了（





-------- 原始邮件 --------
发件人： 云游君 <notifications@github.com>
日期： 2020年8月5日周三 19:51
收件人： YunYouJun/hexo-theme-yun <hexo-theme-yun@noreply.github.com>
抄送： Leo Lingfeng Li <lilingfeng0408@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [YunYouJun/hexo-theme-yun] [Feature Request]建议提高主题兼容性 (#52)

我的 QQ 内置浏览器、QQ 浏览器与小米浏览器测试正常，我觉得更可能与安卓系统 Webview 版本，网络环境及浏览器自身的屏蔽策略有关。

主题开发时，的确多选择最新语法特性，中途为了兼容问题，也有重构过，均使用 caniuse<https://caniuse.com/> 里大部分浏览器支持的特性。做过多兼容（比如 IE 的级别），会有冗余代码，看起来不优雅，所以不打算花时间在这上面。

以及华为似乎好像有挺多这种情况？

https://cn.club.vmall.com/huawei/game/web.php?mod=viewthread&tid=22405779
https://cn.ui.vmall.com/thread-22916552-1-1.html

―
