### ISSUE TITLE
[Usage Problem]hexo5.0.0下reward显示问题

### ISSUE THREAD

**Issue by Sknp1006** [YunYouJun/hexo-theme-yun#53]
您需要提供的内容：

- 主题版本号（必须）： v0.9.5
- 您遇到的问题（必须）： 无法正常渲染reward，yun.yml配置正常。在hexo5.0.0下，除about文件夹下的文件，其余的md文件均不能正常显示reward
  - https://github.com/Sknp1006/hexo_source.git
  - https://sknplz.xyz （当前为hexo@5.0.0）
- 您期待的结果（必须）：希望在hexo5.0.0下，reward能像hexo@4.2.1一样显示
- 您所尝试的操作（可选）：
  - 移除了valine，hexo-renderer-ejs，hexo-helper-live2D，hexo-admin未达到预期效果
  - hexo-filter-file-link对reward显示无影响
  - yun主题已重装master v0.9.5版本

以上，感谢您的帮助( •̀ ω •́ )y

您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by Sknp1006** [comment]
版本更换为v0.9.5 dev可以正常实现。

**Comment by YunYouJun** [comment]
🤣 也就是说已经解决了？ 明天将 release v0.9.6。
