### ISSUE TITLE
[Usage Problem]hexo@5.0.0下reward的显示问题

### ISSUE THREAD

**Issue by Sknp1006** [YunYouJun/hexo-theme-yun#54]
很抱歉上一篇issues我判断失误，以为解决了，再提一下

您需要提供的内容：

- 主题版本号（必须）： v0.9.5
- 您遇到的问题（必须）： 现在已知v0.9.5的master版本与dev版本在hexo@5.0.0下无法正常渲染reward，在正常情况下reward会正常显示。但是在hexo@5.0.0下，需要手动在文章中enable才能显示（除about文件夹内的文件）
  - 代码仓库（可选）：https://github.com/Sknp1006/hexo_source.git
  - 线上预览地址（可选）：https://sknplz.xyz  （线上为hexo@4.2.1）
- 您期待的结果（必须）：希望在hexo@5.0.0下的reward能正常显示
- 您所尝试的操作（可选）：
  - 移除hexo-admin，valine，hexo-renderer-ejs，并未发现对reward的影响
  - 重新安装hexo-filter-file-link，并未发现对reward的影响

以上，再次感谢您的帮助( •̀ ω •́ )y
您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by Sknp1006** [comment]
值得一提的是，在本地浏览一切正常，只有当hexo g时，生成的html中缺少reward相关元素

**Comment by YunYouJun** [comment]
我 clone 你的项目，尝试了 hexo 4.2.0 和 hexo 5.0.0，`hexo s` 与 `hexo g` 均正常显示 `reward`。
我无法复现你的问题。

有什么报错显示的完整截图？

**Comment by Sknp1006** [comment]
![QQ图片20200807230209](https://user-images.githubusercontent.com/41496773/89659153-0aa57900-d902-11ea-9eb6-67f21326a924.png)
完美解决，感谢yox，可能是win10与mac平台的差异导致的，注释图中的两行代码就ok了
