### ISSUE TITLE
[Usage Problem]亮暗模式无法随时切换

### ISSUE THREAD

**Issue by ukityh** [YunYouJun/hexo-theme-yun#55]
我又遇到问题了请救救孩子

您需要提供的内容：

- 主题版本号： v0.9.6
- 您遇到的问题： 尝试添加了dark mode，配置成auto，发现只能在进入网站还没进行别的操作前切换，这个时候是可以随意切换的（本地调试时就是这样）。但是只要进行了别的操作后就切换不了了，和示例站点不太一样，示例站点是可以随时切换的。
- 您期待的结果：我希望可以做到像示例站点那样随时切换亮暗模式
- 您所尝试的操作：升级/重新安装主题，重装node_modules

您所提供的内容越详细，越能够尽快得到你想要的解答。

非常感谢！！！！

**Comment by ukityh** [comment]
并且采用auto后页面有时会显示不正确（banner文字分散到页面两侧，首页文章block消失），刷新后正常

**Comment by YunYouJun** [comment]
尝试您的线上网址 <https://ukityh.github.io/> （是这个么），亮暗按钮可以正常切换。
还是说另有所指？

**Comment by ukityh** [comment]
那也许是coding的问题？托管在coding上的那个页面就不可以www.ukityh.cn

**Comment by ukityh** [comment]
我尝试了一下GitHub的也不可以，是指有所操作后，比如进入了文章页面或者点开分类再回主页后就无法切换了

**Comment by YunYouJun** [comment]
应该是开启了 pjax 的缘故，没有重新加载相关的 js 文件。
我尝试修复一下，你也可以先关闭 pjax 以恢复正常。

**Comment by ukityh** [comment]
好的！！！非常感谢您！！！！

**Comment by YunYouJun** [comment]
@ukityh 已在 https://github.com/YunYouJun/hexo-theme-yun/commit/4ffeab644a3a5d13b614716f51bf8d9471acda22 中修复，您可以尝试拉取最新的 dev 分支。

有任何问题欢迎反馈。
