### ISSUE TITLE
进入文章页面时侧边栏的显示问题

### ISSUE THREAD

**Issue by ZhouYC404** [YunYouJun/hexo-theme-yun#56]
昨天刚开始用hexo，这是我用的第一个主题，很喜欢这种简约的风格哈哈；
调样式的时候遇到了bug，进入文章页面时侧边栏的目录没办法正常显示，而且侧边栏上两个大按钮点击后也没有反应：
![Snipaste_2020-08-12_12-35-33](https://user-images.githubusercontent.com/69456034/89975553-a1728c80-dc98-11ea-883e-7b14b2846e13.png)
不知道文字能否解释清楚，这是我的网站：http://ycgod.gitee.io/blog/

**Comment by ZhouYC404** [comment]
我在本地调试的时候有小概率能显示目录和点击正常，大概50次能有一次。_(:з」∠)_

**Comment by YunYouJun** [comment]
看起来是 Hexo 的问题，此前我无法复现。
但当我将 Hexo 从 `v5.0.0` 升级至 `v5.0.2` 时，成功复现。
还在排查中...

**Comment by YunYouJun** [comment]
已修复，您可以先 clone dev 分支使用，正式版将稍晚一些发布。

**Comment by ZhouYC404** [comment]
好的，谢谢啦
