### ISSUE TITLE
class和id一样的标签怎么分别给样式呢？

### ISSUE THREAD

**Issue by ZhouYC404** [YunYouJun/hexo-theme-yun#57]
老哥我又来了！
这次是一个强迫症问题，不是bug哈；
我发现标签页、分类页和两个about页面的class和id都是一样的，我想做到只给标签页和分类页设置背景图片，而about两个页面不受影响怎么做才好？

其实是一开始的时候我给class为page的标签设置背景图，本意是要给标签页和分类页一个背景的，但是当切换到about页面时，发现背景也是这张图片，并且由于博文很长这张图片失真变得很难看了。。。

只会点css，不知道咋办了，救救孩子吧_(:з」∠)_

**Comment by YunYouJun** [comment]
你可以单独在 about 页面（文章中）添加没有背景图的 css，以只在 about 页面覆盖 CSS。

**Comment by ZhouYC404** [comment]
就是在markdown中加入css吗？

**Comment by YunYouJun** [comment]
嗯。

**Comment by ZhouYC404** [comment]
了解了，谢啦。

**Comment by ZhouYC404** [comment]
最最最后一个小问题，就不单独开issue了，请问搜索页面的这个小叉怎么改颜色？我给color和fill属性都没用，其他图标都能改，拜托啦🙏！
![Snipaste_2020-08-15_12-37-27](https://user-images.githubusercontent.com/69456034/90305338-1c83af00-def4-11ea-839e-ea62aba4820c.jpg)

**Comment by YunYouJun** [comment]
```html
<span class="popup-btn-close close-icon hty-icon-button"></span>
```

```css
.popup .close-icon {
  color: red;
}
```

**Comment by ZhouYC404** [comment]
ok，再次感谢~~~
