### ISSUE TITLE
[Feature Request] 对某些页面/文件不渲染

### ISSUE THREAD

**Issue by huanruomengyun** [YunYouJun/hexo-theme-yun#58]
如果我在 source/xxx/ 下新建一个 index.html 文件，在 hexo g 后会被自动渲染，从而导致实际网页显示效果异常。
希望增加一个功能，可以选择不渲染某个页面或者某个文件。

**Comment by YunYouJun** [comment]
这本质是 Hexo 的工作，修改 `Hexo 文件夹下/_config.yml` 文件配置即可。

```yml
skip_render:
  - README.md
```
