### ISSUE TITLE
侧边栏名称 和站点名称怎么修改

### ISSUE THREAD

**Issue by McQueenMI4** [YunYouJun/hexo-theme-yun#62]
<img width="400" alt="截屏2020-09-05 下午10 25 14" src="https://user-images.githubusercontent.com/51505024/92307178-f1f2b680-efc6-11ea-9363-e959860fb78e.png">

**Comment by YunYouJun** [comment]
见 hexo 目录下 `_config.yml` 的 `title` 与 `author` 字段。
