### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by qingzinai** [YunYouJun/hexo-theme-yun#64]
blog: 紫奈の肥宅屋
url: https://www.qingzinai,github.io
avatar: https://qingzinai.github.io/images/Dorothy.jpg # 
desc: # 呐呐呐

**Comment by YunYouJun** [comment]
示例站点请在 [Demo Sites](https://github.com/YunYouJun/hexo-theme-yun/issues/3) 留言。
