### ISSUE TITLE
[Bug Report]Pjax开启后老婆页面无法正常显示

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#66]
Pjax开启后老婆页面无法正常显示，需要手动刷新。

**Comment by YunYouJun** [comment]
能否提供示例页面？是否使用的 json 形式加载？

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/586cf5a45fde972d4d80237006d667ee0dab6218.
