### ISSUE TITLE
[Usage Problem] minivaline 4 已不再支持QQ头像

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#67]
Since the QQ avatar API exposes the user's mailbox, the function of QQ avatar is deleted in MiniValine version 4.x.
- https://github.com/MiniValine/MiniValine/blob/master/.github/FAQ.md#how-to-improve-the-security-of-minivaline
建议在配置中删除该配置，或切换至minivaline 3.

**Comment by YunYouJun** [comment]
Yeah, thanks. Has removed `enableQQ` for minivaline.
