### ISSUE TITLE
[Feature Request] 为代码添加复制按钮

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#69]
prism.js代码高亮可否增加复制按钮？Orz
这样多行复制代码可能会方便一点。

**Comment by YunYouJun** [comment]
最近比较忙，先咕一会儿，之后写。

**Comment by YunYouJun** [comment]
Completed in https://github.com/YunYouJun/hexo-theme-yun/commit/48becdcc7501b76298c512c6ae4016c0fbac6c94.
