### ISSUE TITLE
功能建议： 博文自动机器翻译

### ISSUE THREAD

**Issue by xmuli** [YunYouJun/hexo-theme-yun#70]
忽然有一个想法，文章的受众不应该被语言局限住～，也有不知无畏～

根据访问者的IP（或者其它信息），判断其所使用的语言，然后能够自动将博客翻译成 其对应国家的语言？
当然，非原文翻译的话（会有一个醒目的机 **机译** 标志， 参考 DeepL、 谷歌翻译、或开源翻译），也有一个按钮，一键切换为 原文（中文）。或者用户自定义选择博客语言（文章对应切机器翻译语言）。

后面能否添加 文章自动翻译为其他语言 的选项，类似于某些官网的网站具有国际化？

不知道实际可行性如何，想法有点天马行空，若是空闲，愿作者考虑之～

**Comment by leostudiooo** [comment]
想法不错 前排占座

**Comment by YunYouJun** [comment]
这个功能过去可以通过谷歌的翻译组件实现，挂载到页面上，并可切换翻译。
> https://translate.google.com/intl/en/about/website/

但我查看了谷歌翻译组件网址，该插件已不再支持用户申请（过去的用户仍可正常使用），而更推荐通过浏览器的翻译功能进行翻译。

网页端翻译，调用相关 API 是最佳的选择，且非中文用户基本无须担心无法访问谷歌的问题。
而除了谷歌，此外似乎也没有更好的实现方式。

是否有其他方案想法？

**Comment by xmuli** [comment]
或者还真的有，有一个插件叫 **沙拉查词** ， ta里面默认自带 谷歌、必应、有道等很多翻译，想必也是使用免费的 API 接口~

**Comment by YunYouJun** [comment]
我尝试使用谷歌 API，但是需要信用卡信息……
考虑到实现及泛用性，该功能以 hexo 插件的形式来实现更为合适。
以及谷歌浏览器本身已带有翻译页面功能，性能还是体验要更为友好，
所以主题层面暂时不会考虑实现该功能。

**Comment by YunYouJun** [comment]
暂时没有想到更好的实现方式，还是浏览器直接翻译更为优雅。
至于 hexo 页面翻译插件，因为我暂时没有该项需求和时间，所以也不会对此进行开发。

如果还有其他更好的方式，欢迎反馈。
该 ISSUE 就先关闭了。
