### ISSUE TITLE
[Feature Request] 昼夜切换新增按照当地时间切换

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#71]
昼夜切换可否新增按照当地时间切换，例如22:00-06:00。

**Comment by YunYouJun** [comment]
此前考虑过这个问题，不过因为用 `prefers-color-scheme` 实现很优雅，所以优先使用了这种方式跟随用户系统来实现。
根据时间判断也很简单，只是意味着用户进入网页时都要走一遍这个逻辑。打算将其作为一个配置项，开启时才会根据时间判断，默认关闭。

目前的设想与此前保持兼容，是作为 mode 的一个可选参数。（当前有 `light|dark|auto`）

`mode: time` 即代表跟随时间进行切换。

是否还有其他关于此的方案建议？

**Comment by YunYouJun** [comment]
dev 分支已尝试添加了该功能，使用方式即 `mode: time`，根据浏览器本地的时间进行判断，早 7:00 - 19:00 为亮，其余为暗模式。虽然也有考虑过再提供自定义时间范围的功能，但还需增加新的配置项，且感觉意义不大，mode 单项更为简洁。

您可以尝试切换至 dev 分支使用，并在该 ISSUE 下反馈。
