### ISSUE TITLE
[Feature Request] 评论系统切换

### ISSUE THREAD

**Issue by QingxuMo** [YunYouJun/hexo-theme-yun#72]
能不能新增一个评论区评论系统手动切换功能，以同时启用多个评论系统。其特性大致如下：

- 默认仅会加载一个评论系统，当访客手动点击切换时（JavaScript）加载另一个评论系统
- 默认同时只会显示一个评论系统，显示评论界面为访客当前选择的评论系统界面

之所以有这个需求是因为最近使用 Valine 小问题不断，打算将评论系统改成 Disqus，但即使有 Disqusjs 也不能解决国内用户无法评论的问题，因此我想将 Disqus 设为主评论系统，Valine 设置为副评论系统。对于可以正常使用且愿意使用 Disqus 的用户使用 Disqus，对于其他用户使用 Valine。

**Comment by YunYouJun** [comment]
实际上我现在正是使用的 valine 和 utterances 切换，本质使用外挂自定义脚本实现。
此前也有考虑过集成进主题，但总感觉逐渐更为臃肿，以及配置尚未确定。

目前一个设想的方案是在 comment 上扩展：

```
comment:
  candidate:
    - disqus
    - valine
```

**Comment by YunYouJun** [comment]
已经在 dev 分支悄悄加上了。

大致使用方式是配置（在 `yun.yml` 里加）：

```yaml
comment:
  candidates:
    - valine
    - utterances
```

实现 valine 与 utterances 多评论切换，默认第一个为显示的评论。（其他类似）
