### ISSUE TITLE
[Feature Request] 请求移植next主题中的tabs功能

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#74]
可见：https://theme-next.js.org/docs/tag-plugins/tabs.html
有的时候还是挺有用的。

**Comment by YunYouJun** [comment]
类似的功能我一直以为是 hexo 的插件来着，感觉如果是插件的形式也更合理。这样大家就可以只要安装插件，在不同的主题中使用。
emm，我需要一些时间考虑一下它的实现方式，之后再着手。

**Comment by YunYouJun** [comment]
该功能已通过 [hexo-tag-common](https://github.com/YunYouJun/hexo-tag-common) 插件形式实现。

> [Demo for tag-common]()

```sh
npm install hexo-tag-common
```

安装即可。

在 `_config.yml` 中配置（选择使用 CDN，还是生成本地文件，默认为 `true`）：

```
tag_common:
  cdn: false
```

当前还比较粗糙，不过 `tabs` 功能还是可以用的，这个插件我以后打算用来放置更多标签扩展。（这意味着即使更换主题，也可以使用此类功能。）~~当然因为都是咱开发的，对本主题肯定适配最好。~~

**Comment by YunYouJun** [comment]
后续关于此的功能建议、BUG 反馈，请到 [Issues | hexo-tag-common](https://github.com/YunYouJun/hexo-tag-common/issues)。
该 ISSUE 就先关闭了。
