### ISSUE TITLE
[Feature Request] 侧边栏增加目录树导航

### ISSUE THREAD

**Issue by jianchengwang** [YunYouJun/hexo-theme-yun#75]
就是侧边栏菜单增加一个目录树，点击，展示站点的目录树结构以及目录下的文章，点击文章的时候，右边的文章内容可以局部刷新，这样对于章节很多的笔记或者小说，可以很方便进行查阅，可以参考[hexo-theme-tree](https://github.com/wujun234/hexo-theme-tree)

**Comment by YunYouJun** [comment]
实际上等价于归档和分类的综合？实现倒是可以实现，只是在想对于博客类主题会不会有些冗余了，这类功能似乎更适合 Vuepress、GitBook 等文档类项目，或者一些笔记软件。

因为我设想的主题能够简洁独特一些，所以只会保留侧边栏和主区块，不会添加顶部或其他的菜单栏。
如果真要增加的话，或许参照 Octotree 的挂件形式也不错。
![image](https://user-images.githubusercontent.com/25154432/94984230-81ff2e00-057c-11eb-9386-07a305d78368.png)
![image](https://user-images.githubusercontent.com/25154432/94984234-87f50f00-057c-11eb-9462-404cf43978fc.png)

而作为挂件的话，甚至可以写成一个通用的插件，以供任意主题使用。实现方式有待考虑，短期内可能还不会实现。
如果有其他想法建议，欢迎反馈。

**Comment by jianchengwang** [comment]
> 实际上等价于归档和分类的综合？实现倒是可以实现，只是在想对于博客类主题会不会有些冗余了，这类功能似乎更适合 Vuepress、GitBook 等文档类项目，或者一些笔记软件。
> 
> 因为我设想的主题能够简洁独特一些，所以只会保留侧边栏和主区块，不会添加顶部或其他的菜单栏。
> 如果真要增加的话，或许参照 Octotree 的挂件形式也不错。
> ![image](https://user-images.githubusercontent.com/25154432/94984230-81ff2e00-057c-11eb-9386-07a305d78368.png)
> ![image](https://user-images.githubusercontent.com/25154432/94984234-87f50f00-057c-11eb-9462-404cf43978fc.png)
> 
> 而作为挂件的话，甚至可以写成一个通用的插件，以供任意主题使用。实现方式有待考虑，短期内可能还不会实现。
> 如果有其他想法建议，欢迎反馈。
![image](https://user-images.githubusercontent.com/15951975/94986852-ab2bb880-0594-11eb-9555-e089ab93a80d.png)
我的想法是文章页的侧边栏上面可以多一个目录菜单的图标，当然这个用户可以自定义是否开启，因为有的博客文章也是一个系列的，比如小说或者学习笔记啥的。`Octotree`的挂件实现当然也可以，就是样式可能跟原博客不搭就是了，也不能适配移动端。

**Comment by YunYouJun** [comment]
所以是点击这个树形按钮，侧边菜单栏变成类似文章目录的树状菜单的意思么？

> 挂件的样式倒是可以自定义，适配移动端倒是也不是啥难事。

因为作为菜单的话势必要修改相关布局内容，挂件的形式倒是可以用插件实现，更为无侵入一点。同时可以跨主题使用。

本身这个功能能访问的页面，实际上通过分类和归档之类的也能访问，所以这个功能的目的应该是旨在便捷。对于无需这个功能的人，也无需加入主题本身。对于需要这个功能的人来说，安装一个插件即可解决，在打算换用其他主题时，也仍然能享用这个功能。更为合理一些。您觉得如何？

> 当然本质对这一类需求比较强的话，其实专门使用 Vuepress/GitBook/Docsify/Docute 额外搭建一个文档类的站点更为理想。

**Comment by jianchengwang** [comment]
> 所以是点击这个树形按钮，侧边菜单栏变成类似文章目录的树状菜单的意思么？
>  对的，挂件也可以把，就是这么一个建议

**Comment by YunYouJun** [comment]
好消息，经过加班加点~~摸鱼~~，插件 [hexo-widget-tree](https://github.com/YunYouJun/hexo-widget-tree) v0.0.1 诞生了。
只需要简单安装插件，即可为站点添加树状菜单预览。按钮默认在页面左边中间。可以设置隐藏模式。自我感觉还不错，想要 PJAX 开启主题的 PJAX 即可。之后功能再慢慢优化吧。
你可以进入 [我的站点](https://www.yunyoujun.cn)，将鼠标放在页面左边的中间，按钮就会浮现，点击查看效果。（不过我站点没开 PJAX，因为放了一些其他测试的页面。）

该 Issue 就先关闭了，后续关于此的功能，可以到 [Issues | hexo-widget-tree](https://github.com/YunYouJun/hexo-widget-tree/issues) 反馈。

**Comment by YunYouJun** [comment]
效果如图：

![image](https://user-images.githubusercontent.com/25154432/95433272-4ef4da00-0982-11eb-9d09-bfec464e5d5b.png)

![image](https://user-images.githubusercontent.com/25154432/95433252-443a4500-0982-11eb-9c51-d17aa41d39df.png)
