### ISSUE TITLE
[Usage Problem] aplayer 设置 autoplay 为 true 的时候 访问网站无法自动播放音乐

### ISSUE THREAD

**Issue by MaiXiaoMeng** [YunYouJun/hexo-theme-yun#76]
您需要提供的内容：

- Hexo 驱动 ：v5.2.0
- 主题版本号（必须）：  v1.2.0
- 您遇到的问题（必须）： aplayer 设置 autoplay 为 true 的时候 访问网站无法自动播放音乐
  - 截图（可选）
    -  yun.yml  http://ww1.sinaimg.cn/large/005QiI8Cgy1gjglz56xwwj308p0evjsh.jpg
    - _config.yml  http://ww1.sinaimg.cn/large/005QiI8Cgy1gjglytdsolj30k0048q4e.jpg
  - 代码仓库（可选）
  - 线上预览地址（可选）
- 您期待的结果（必须）：我希望可以在访问网站的时候 aplayer 可以自动播放音乐，不需要点击
- 您所尝试的操作（可选）：我尝试了 xxx，但是 xxx。

您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by YunYouJun** [comment]
该问题是谷歌浏览器以及现在大部分浏览器的安全策略问题，以避免未经许可的网站擅自播放（~~奇怪的~~）声音。主题层面无法解决。

> [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

**Comment by MaiXiaoMeng** [comment]
> 该问题是谷歌浏览器以及现在大部分浏览器的安全策略问题，以避免未经许可的网站擅自播放（~奇怪的~）声音。主题层面无法解决。
> 
> > [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)

因为我使用全局的播放模式，那是否可以在访问网站的时候检测用户操作行为的时候实现自动播放呢?(比如: 点击首页标语动画的下面的箭头的时候，或者监测鼠标滚轮滚动的时候)

**Comment by YunYouJun** [comment]
实际上在播放器加载前有操作就会自动播发。添加鼠标监测滚动等触发，代码实在过于冗余了，也影响性能。且即便要做，应当由播放器本身监听更为合理。所以不会实现这个功能。
