### ISSUE TITLE
几处样式微调应该更好哦！

### ISSUE THREAD

**Issue by VemboLiu** [YunYouJun/hexo-theme-yun#8]
1. 第一是在部分尺寸下，sidebar的按钮和search的按钮和文章的标题会有重叠，比如
![avatar](https://s1.ax1x.com/2020/03/24/8L3KhD.png)

2. 侧边的头像区下移一些应该更好看呢！
![avatar](https://s1.ax1x.com/2020/03/24/8L3Q9e.png)

另：确实很好看哦！

**Comment by YunYouJun** [comment]
谢谢你的建议。
第一点，我将下移移动端的标题位置来调整。
第二点，其实本来是想有点像米老鼠那样的感觉，不过确实有些奇怪，我将添加一个配置选项来供用户自行决定是否开启。

---

顺带一提，这里是个意外。
![image](https://user-images.githubusercontent.com/25154432/77419494-767bbf00-6e03-11ea-8eb1-ecd128be9a02.png)
实际效果应该是这样。
![image](https://user-images.githubusercontent.com/25154432/77419643-b9d62d80-6e03-11ea-825e-4ee97ecf4283.png)
单纯因为 CDN 缓存没有更新……

**Comment by YunYouJun** [comment]
Hello, 关于上述问题已修复。您可以访问我的[小站](https://www.yunyoujun.cn)查看。（需要 Ctrl + F5 强制刷新缓存）
我就先关闭该 Issue 了～
如果您对此还有其他想法，您可以随时重新开启它。谢谢！
