### ISSUE TITLE
[Feature Request] 添加网站预加载动画功能

### ISSUE THREAD

**Issue by flottant** [YunYouJun/hexo-theme-yun#80]
添加网站预加载动画功能，即在究极龟速的网络环境下显示例如“加载中”的页面。

**Comment by YunYouJun** [comment]
🤣 我是想加来着，然后我 chrome 调试时 slow 3G，发现如果连页面都加载不出来的话，那么加载动画也来不及显示，加载动画可以显示的时候，页面也基本瞬间完成了。其次大部分加载通常用于动态网站，所以有明确的响应来判断加载状态。（你可以看[我的老婆](https://www.yunyoujun.cn/girls/)页面，这种有异步请求的更适合展示加载动画。）静态加载成功的时候页面也随之好了，加载动画又显得有些多余。

所以最后还是不加了。（
