### ISSUE TITLE
[Usage Problem] 在开启PJAX的时候，全局播放器在使用搜索功能的时候可以无法持续播放音乐

### ISSUE THREAD

**Issue by MaiXiaoMeng** [YunYouJun/hexo-theme-yun#81]
您需要提供的内容：

- 主题版本号（必须）：  Yun v1.2.0
- 您遇到的问题（必须）： 在开启PJAX的时候，全局播放器在切换页面的时候可以正常持续播放音乐，但一使用搜索功能的时候，点击搜索出来的文章的后，全局播放器将会停止播放音乐且切换页面也无法持续播放音乐。
  - 截图（可选）
  - 代码仓库（可选）
  - 线上预览地址（可选）https://www.xiaomeng.live
- 您期待的结果（必须）：我希望使用搜索功能的时候，点击搜索出来的文章的后全局播放器会持续播放音乐，不中断
- 您所尝试的操作（可选）：- 1. 未修改 Yun 主题的任何代码 2. 停止 hexo 的 _conifg.yml 里面的 search 配置后 恢复正常，但搜索功能无法使用
![search 配置](http://ww1.sinaimg.cn/large/005QiI8Cgy1gjlw6bexiyj30vl057jsb.jpg)

**Comment by YunYouJun** [comment]
抱歉，该功能不会实现。
为不影响访问速度，本地搜索在所有页面完全加载后才会初始化，位于 PJAX 的初始化之后。专门为本地搜索重新初始化也显然过于冗余。此外搜索框因为铺至整个页面大小，如果仍有 PJAX 则会出现点击页面，后面的页面加载了，用户却以为没有加载的情况。不如索性重新加载。

**Comment by MaiXiaoMeng** [comment]
> 抱歉，该功能不会实现。
> 为不影响访问速度，本地搜索在所有页面完全加载后才会初始化，位于 PJAX 的初始化之后。专门为本地搜索重新初始化也显然过于冗余。此外搜索框因为铺至整个页面大小，如果仍有 PJAX 则会出现点击页面，后面的页面加载了，用户却以为没有加载的情况。不如索性重新加载。

好吧，那这个全局播放器存在的意义是啥，总不能在听音乐的时候听着听着点击搜索一下就停止了吧，这才是影响用户的体验

**Comment by YunYouJun** [comment]
因为搜索本身就不是频繁的操作，除了搜索之外，所有的页面切换、链接跳转均不影响。
此外全局播放器本身未必便没有太大意义，无非是分享一些自己喜欢的音乐，放在特定的页面也足矣，比如我就没开全局播放器……倒不如说常年静音的我觉得放全局播放器才是影响体验。
