### ISSUE TITLE
[Bug Report]文章分类的显示无法支持同层多分类

### ISSUE THREAD

**Issue by Shimogawa** [YunYouJun/hexo-theme-yun#82]
如题。

Hexo支持多分类：
![RH~Q~ZR)F1IVX% }~C1CXIM](https://user-images.githubusercontent.com/23229568/96334257-ef917b00-10a1-11eb-9dcf-58d3fbcb082f.png)

但是页面显示不支持，会显示成子分类的形式：
![WBR{1%W1E__TK6J}F9OCKB0](https://user-images.githubusercontent.com/23229568/96334244-df799b80-10a1-11eb-8f90-4d9a0e344eb8.png)
![72GP9@SX@P1M5IVOF7_OH54](https://user-images.githubusercontent.com/23229568/96334263-0041f100-10a2-11eb-824c-e758e1709b87.png)

**Comment by YunYouJun** [comment]
已支持为同篇文章设置多个分类。

> 但个人角度更建议单篇文章只设置单个分类，而通过多个标签进行描述。
