### ISSUE TITLE
[Feature Request] 希望大佬加一个中英文切换的功能

### ISSUE THREAD

**Issue by weiranfu** [YunYouJun/hexo-theme-yun#87]
**Is your feature request related to a problem? Please describe.**
在用大佬的theme的时候，选择自定义主题语言的时候就很纠结，还有About 和About Site两个界面的主题语言也很纠结，
想同时提供中英文两个版本的界面

**Describe the solution you'd like**
希望有一个位于主界面上方的languages按钮，可以选择站点所使用的语言。
例如选择英文的话，主题语言包将使用英文。About 和 About Site 界面也将加载英文版界面。

**Comment by YunYouJun** [comment]
这个此前的确有考虑过，不过因为似乎没什么需求（~~懒~~）就搁置了。切换中英文的话，同时意味着文章的内容，也最好有对应的中英文翻译的版本。（此前谷歌有一个网页翻译的挂件，但已经停止申请了，所以也不再考虑。）

中英文多语的话，应该是考虑通过路径来区分，如默认关于页面为 `/about/` 则对应英文链接为 `/en/about/`，相关需要考虑的内容较多，所以可能需要等待较长一段时间才会实现。

**Comment by YunYouJun** [comment]
看起来这个插件已经能解决我此前想到的问题，此后考虑基于此做主题的适配。(比如语言切换按钮)
https://github.com/Jamling/hexo-generator-i18n

**Comment by weiranfu** [comment]
> 看起来这个插件已经能解决我此前想到的问题，此后考虑基于此做主题的适配。(比如语言切换按钮)
> https://github.com/Jamling/hexo-generator-i18n

感谢云游君，这个插件是挺好，我去研究研究
