### ISSUE TITLE
文章摘要中的数学公式不会被识别

### ISSUE THREAD

**Issue by ADD-SP** [YunYouJun/hexo-theme-yun#9]
OS：Windows10 X64 1909
浏览器：Microsoft Edge 80.0.361.69 (官方内部版本) (64 位)
使用master分支和dev分支均有此问题。不知道是插件的问题还是主题的问题或是HEXO自己的问题。

```
title: 计算机组成原理-总线结构
katex: true
categories:
  - 学习笔记
  - 计算机组成原理
date: 2020-03-26 02:14:47

## 概述

\\(s_n\\)

列举并简要分析如下5种总线结构：
+ 一种单总线结构
+ 一种双总线结构
+ 两种三总线结构
+ 一种四总线结构

<!--more-->
```

![Snipaste_2020-03-26_03-43-13](https://user-images.githubusercontent.com/44437200/77578969-6b648400-6f14-11ea-93b2-569ca955664c.png)
![Snipaste_2020-03-26_03-43-26](https://user-images.githubusercontent.com/44437200/77578973-6d2e4780-6f14-11ea-854f-e2ed5a2776f9.png)

**Comment by YunYouJun** [comment]
是的，因为咱当时就是这么设计的……
> 如果在主页显示，就意味着主页要加载 KaTex 那么大的库，会影响加载速度。
是我有点自作主张了。

此后将添加一个是否开启在主页加载 KaTex 库的选项。

![C31F870A4A07CDBAC1526CD97C490E48](https://user-images.githubusercontent.com/25154432/77579477-5b00d900-6f15-11ea-91f5-5fad8d053fbc.jpg)

（等我睡醒就加！）

> 话说这个表情甚至有点萌

**Comment by ADD-SP** [comment]
> 是的，因为咱当时就是这么设计的……
> 
> > 如果在主页显示，就意味着主页要加载 KaTex 那么大的库，会影响加载速度。
> > 是我有点自作主张了。
> 
> 此后将添加一个是否开启在主页加载 KaTex 库的选项。
> 
> ![C31F870A4A07CDBAC1526CD97C490E48](https://user-images.githubusercontent.com/25154432/77579477-5b00d900-6f15-11ea-91f5-5fad8d053fbc.jpg)
> 
> （等我睡醒就加！）
> 
> > 话说这个表情甚至有点萌 \(s_n\)

emmm，6个小时前，莫非宁也是修仙中人？

**Comment by YunYouJun** [comment]
@ADD-SP 
> emmm，回复时间6个小时前，莫非宁也是修仙中人？
彼此彼此。hhh
已添加 KaTeX 开启全局加载的选项（默认关闭），可以 `clone` 最新版的 dev 分支使用，并参见文档手动开启它。

在 `yun.yml` 中

```yml
katex:
  global: true
```
> https://yun.yunyoujun.cn/guide/third-party-support.html#katex

我将关闭此 ISSUE，如果你对此还有任何问题，你可以重新打开它。谢谢！
