### ISSUE TITLE
开启minivaline会导致页面字体css被minivaline覆盖

### ISSUE THREAD

**Issue by shzxm** [YunYouJun/hexo-theme-yun#92]
开启minivaline会导致页面字体css被minivaline覆盖

在配置文件中 评论系统 开启 minivaline会导致 md字体颜色被覆盖.

全站 文章类 字体变成灰色

主题配置为 

mode:dark

minivaline配置为

minivaline:
  enable: false
  appId: 123
  appKey: 123
  placeholder: Write a Comment
  adminEmailMd5:
  math: true 
  md: true 

  lang:

查询 minivaline文档 https://minivaline.js.org/docs/cn/#/Options?id=mode

默认配置 dark为false

在打开 或者 关闭 dark模式的情况下

上述问题依旧无法解决

![image](https://user-images.githubusercontent.com/9905297/103137562-daba0f00-4704-11eb-9423-ab9fd007da45.png)

主题版本号（必须）： v1.3.0

**Comment by YunYouJun** [comment]
测试确实存在这个问题。但查看 CSS 样式，原因为 `minivaline` 使用了 `.markdown-body` 这一通用的命名空间，并挂载为内联的 `<style>`，因此建议向 minivaline 提 Issue，使用添加命名空间等解决方案，如 `.minivaline .markdown-body`。而非由主题针对评论增加冗余的样式适配。

**Comment by MHuiG** [comment]
minivaline 也不想增加冗余的样式适配，所以直接关掉就好了

```
closeMarkdownStyle: true
```

**Comment by shzxm** [comment]
> minivaline也不想增加冗余的样式适应，所以直接关掉就好了
> 
> ```
> closeMarkdownStyle: true
> ```

居然没有看到这个配置选项 
感谢作者~
