### ISSUE TITLE
切换暗黑模式貌似有bug？

### ISSUE THREAD

**Issue by SomeSama** [YunYouJun/hexo-theme-yun#94]
### F5刷新前 
![image](https://user-images.githubusercontent.com/50948638/103422364-0729cb80-4bdc-11eb-9dd2-adb25364bfd0.png)

### 刷新后
![image](https://user-images.githubusercontent.com/50948638/103422394-2cb6d500-4bdc-11eb-90d8-a74d3578f809.png)

**Comment by YunYouJun** [comment]
已修复，请切换至 dev 分支。
将在未来统一释出至稳定版。
