### ISSUE TITLE
[Bug Report] 标签使用词云时，第一次点击加载不显示，需要刷新才会显示

### ISSUE THREAD

**Issue by SomeSama** [YunYouJun/hexo-theme-yun#95]
#### 第一次点击加载时
![image](https://user-images.githubusercontent.com/50948638/103462605-61a06480-4d61-11eb-8953-f2ed7c70ff81.png)
#### 刷新后
![image](https://user-images.githubusercontent.com/50948638/103462609-6cf39000-4d61-11eb-8dc9-63666bfc4462.png)

**Comment by YunYouJun** [comment]
抱歉，无法复现，本地测试正常。能否提供线上可预览链接。

**Comment by SomeSama** [comment]
我的站点blog.jcareer.io，尝试开启pajax试试？我的配置是开启pajax的
________________________________

**Comment by YunYouJun** [comment]
已修复。
