### ISSUE TITLE
hexo g时报错

### ISSUE THREAD

**Issue by youthriverside** [YunYouJun/hexo-theme-yun#96]
- 主题版本号： v1.3.0
- 遇到的问题： hexo g时报错

![image](https://user-images.githubusercontent.com/63176620/103470739-ec5c8000-4db0-11eb-88bd-6a463c7dc040.png)
- 期待的结果：我希望能够指点鄙人二三，使得新主题可用
- 所尝试的操作：我尝试按照教程重新操作，但并无大用

**Comment by YunYouJun** [comment]
`color` 配置项丢失。

请在 `yun.yml` 中进行配置，请勿直接更改主题任何文件。

建议删除主题，重新 clone。
