### ISSUE TITLE
[yun version 1.3.0 本地搜索的路径有问题，不知道应该怎么修改]

### ISSUE THREAD

**Issue by mikutown** [YunYouJun/hexo-theme-yun#98]
您需要提供的内容：

- 主题版本号（必须）： v1.3.0
- 您遇到的问题（必须）： 我遇到了本地搜索生成链接多了一个根路径的字符串的问题。
 比如说一篇文章的路径是：https://mikutown.gitee.io/blog/2020/03/30/MarkDown%E5%85%A5%E9%97%A8/
 但是通过本地搜索后：https://mikutown.gitee.io/blog//blog/2020/03/30/MarkDown%E5%85%A5%E9%97%A8/ 就报404了
我的_config.yml也没写多余的路径，但是本地搜索会自动加一个/blog/，不知道去哪里修改，希望大神可以帮帮我！
- 您期待的结果（必须）：我希望能让本地搜索得到的路径变成正常文章的路径。
- 您所尝试的操作（可选）：我尝试了 xxx，但是 xxx。

您所提供的内容越详细，越能够尽快得到你想要的解答。

**Comment by mikutown** [comment]
我自己把v1.2.0的localsearch文件替换了，现在功能正常了！

**Comment by YunYouJun** [comment]
Thanks. Fixed in https://github.com/YunYouJun/hexo-theme-yun/commit/63b55e546735ba56c45b788603153e7f0de8aa69.

**Comment by mikutown** [comment]
Roger
